.\"Created with GNOME Manpages Editor Wizard
.\"http://gmanedit.sourceforge.net
.\"Sergio Rua <srua@gpul.org>
.\"
.TH ecore_config 1 "January 18, 2007" "Ecore"

.SH NAME
ecore_config \-that allow creation and editing of ecore_config databases

.SH SYNOPSIS
.B ecore_config
.RI \-a\ |\ \-k\ [\-g|\-d|\-b|\-f|\-i|\-r|\-s|\-t]\ [\-c]
.br

.SH DESCRIPTION
.PP
\fBecore_config\fP is a tool that allows creation and editing of 
ecore_config databases used by the programs relying on libecore

.SH OPTIONS
\fIecore_config\fP accepts the following options:
.TP
.B \-c, \-\-file=FILE
Specify the config file to read
.TP
.B \-k, \-\-key=KEY
Select the key KEY. Must be given for all commands except \-a
.TP
.B \-g, \-\-get
get key
.TP
.B \-d, \-\-del
delete key
.TP
.B \-b, \-\-bool=VALUE
set boolean
.TP
.B \-f, \-\-float=VALUE
set float
.TP
.B \-i, \-\-int=VALUE
set integer
.TP
.B \-r, \-\-rgb=VALUE
set RGBA
.TP
.B \-s, \-\-string=VALUE
set string
.TP
.B \-t, \-\-theme=VALUE
set theme
.SH AUTHOR
This manual page was written by Albin Tonnerre <albin.tonnerre@gmail.com> 
for the Debian GNU/Linux system (but may be used by others).
