.TH EDJE_RECC 1 "Jan 30, 2007" "0.5.0.042" "The edje recompiler"
.SH NAME
edje_recc \- an edje recompiler
.SH SYNOPSIS
.B edje_recc
.RI [\| OPTIONS \|]
.B input_file.edj
.SH DESCRIPTION
edje_recc is a recompiler for edje files.
.SH EXAMPLES
edje_recc -v file.edj
.SH OPTIONS
.B -v
Verbose output
.P
.B -no-lossy
Do NOT allow images to be lossy
.P
.B -no-comp
Do NOT allow images to be stored with lossless compression
.P
.B -no-raw
Do NOT allow images to be stored with zero compression (raw)
.P
.BI -min-quality " \|VAL
Do NOT allow lossy images with quality < VAL (0-100)
.P
.BI -max-quality " \|VAL
Do NOT allow lossy images with quality > VAL (0-100)
.SH SEE ALSO
edje_cc(1)
.BR
edje_decc(1)
.SH BUGS
Please reports bugs to the Pkg-E Team <pkg-e-devel@lists.alioth.debian.org>
.SH AUTHOR
This man page was written by Ronald Claveau for the Debian GNU/Linux system (but may  be  used by others).
