.TH EDJE_CC 1 "Jan 29, 2007" "0.5.0.042" "The edje compiler"
.SH NAME
edje_cc - an edje compiler
.SH SYNOPSIS
.B edje_cc
.RI [\| OPTIONS \|]
.B input_file.edc
.RI [\| output_file.edj \|]
.SH DESCRIPTION
edje_cc is a compiler for edje files
.SH EXAMPLES
edje_cc -v file.edc
.SH OPTIONS
.BI \-id " \|image/directory
Add a directory to look in for relative path images
.P
.BI \-fd " \|font/directory
Add a directory to look in for relative path fonts
.P
.B \-v
Verbose output
.P
.B \-no\-lossy
Do NOT allow images to be lossy
.P
.B \-no\-comp
Do NOT allow images to be stored with lossless compression
.P
.B \-no\-raw
Do NOT allow images to be stored with zero compression (raw)
.P
.BI \-min\-quality " \|VAL
Do NOT allow lossy images with quality < VAL (0-100)
.P
.BI \-max\-quality " \|VAL
Do NOT allow lossy images with quality > VAL (0-100)
.P
.BI \-Ddefine_val= " \|to
CPP style define to define input macro definitions to the .edc source
.SH SEE ALSO
edje_decc(1)
.BR
edje_recc(1)
.SH BUGS
Please reports bugs to the Pkg-E Team <pkg-e-devel@lists.alioth.debian.org>
.SH AUTHOR
This man page was written by Ronald Claveau for the Debian GNU/Linux system (but may  be  used by others).
