"#ifdef GL_ES\n"
"#ifdef GL_FRAGMENT_PRECISION_HIGH\n"
"precision highp float;\n"
"#else\n"
"precision mediump float;\n"
"#endif\n"
"#endif\n"
"uniform sampler2D tex;\n"
"uniform sampler2D texa;\n"
"varying vec2 coord_c;\n"
"varying vec2 coord_a;\n"
"void main()\n"
"{\n"
"   gl_FragColor.rgb = texture2D(tex, coord_c.xy).rgb * texture2D(texa, coord_a).g;\n"
"   gl_FragColor.a   = texture2D(texa, coord_a).g;\n"
"}\n"
