#ifndef __ECORE_COCOA_CURSOR_H__
#define __ECORE_COCOA_CURSOR_H__

typedef enum
{
   ECORE_COCOA_CURSOR_ARROW                     = 0,
   ECORE_COCOA_CURSOR_CONTEXTUAL_MENU,
   ECORE_COCOA_CURSOR_CLOSED_HAND,
   ECORE_COCOA_CURSOR_CROSSHAIR,
   ECORE_COCOA_CURSOR_DISAPPEARING_ITEM,
   ECORE_COCOA_CURSOR_DRAG_COPY,
   ECORE_COCOA_CURSOR_DRAG_LINK,
   ECORE_COCOA_CURSOR_IBEAM,
   ECORE_COCOA_CURSOR_OPEN_HAND,
   ECORE_COCOA_CURSOR_OPERATION_NOT_ALLOWED,
   ECORE_COCOA_CURSOR_POINTING_HAND,
   ECORE_COCOA_CURSOR_RESIZE_DOWN,
   ECORE_COCOA_CURSOR_RESIZE_LEFT,
   ECORE_COCOA_CURSOR_RESIZE_LEFT_RIGHT,
   ECORE_COCOA_CURSOR_RESIZE_RIGHT,
   ECORE_COCOA_CURSOR_RESIZE_UP,
   ECORE_COCOA_CURSOR_RESIZE_UP_DOWN,
   ECORE_COCOA_CURSOR_IBEAM_VERTICAL,

   __ECORE_COCOA_CURSOR_LAST, /* Sentinel */

   ECORE_COCOA_CURSOR_DEFAULT = ECORE_COCOA_CURSOR_ARROW

} Ecore_Cocoa_Cursor;

#endif /* ! __ECORE_COCOA_CURSOR_H__ */

