dnl use: EFL_ENABLE_EO_API_SUPPORT
AC_DEFUN([EFL_ENABLE_EO_API_SUPPORT],
[
  AC_DEFINE([EFL_EO_API_SUPPORT], [1], [Enable access to unstable EFL Eo API])
])

dnl use: EFL_DISABLE_LEGACY_API_SUPPORT
AC_DEFUN([EFL_DISABLE_LEGACY_API_SUPPORT],
[
  AC_DEFINE([EFL_NOLEGACY_API_SUPPORT], [1], [Disable legacy EFL API])
])

