CC=gcc
COMMON_FLAGS=`pkg-config --libs --cflags eina,ecore,evas,ecore-evas,emotion`

EXAMPLES= emotion_basic_example \
          emotion_border_example \
          emotion_generic_example \
          emotion_generic_subtitle_example \
          emotion_signals_example

all: examples
examples: $(EXAMPLES)

$(EXAMPLES):
	$(CC) -o $@ $@.c $(COMMON_FLAGS)

clean:
	@echo "Cleaning up built objects..."
	@rm -Rf $(EXAMPLES)
