CC=gcc
COMMON_FLAGS=`pkg-config --libs --cflags eina,ecore,ethumb,ethumb_client`

EXAMPLES= ethumb_dbus

all: examples
examples: $(EXAMPLES)

$(EXAMPLES):
	$(CC) -o $@ $@.c $(COMMON_FLAGS)

clean:
	@echo "Cleaning up built objects..."
	@rm -Rf $(EXAMPLES)
