CC=gcc
COMMON_FLAGS=`pkg-config --libs --cflags eina, emile`

EXAMPLES= emile_base64

all: examples
examples: $(EXAMPLES)

$(EXAMPLES):
	$(CC) -o $@ $@.c $(COMMON_FLAGS)

clean:
	@echo "Cleaning up built objects..."
	@rm -Rf $(EXAMPLES)
