CC=gcc
COMMON_FLAGS=`pkg-config --libs --cflags ecore,eio`

EXAMPLES= eio_file_copy \
          eio_file_ls

all: examples
examples: $(EXAMPLES)

$(EXAMPLES):
	$(CC) -o $@ $@.c $(COMMON_FLAGS)

clean:
	@echo "Cleaning up built objects..."
	@rm -Rf $(EXAMPLES)
