#!/bin/sh
cp ./emotion.c.in ./emotion.c
for I in `find ./src/lib -name "Emotion.h" -print`; do
  cat $I >> ./emotion.c
done
#for I in `find ./src/lib -name "*.c" -print`; do
#  cat $I >> ./emotion.c
#done
rm -rf ./doc/html ./doc/latex ./doc/man
doxygen
cp doc/img/*.png doc/html/
cp doc/img/*.gif doc/html/
rm -f emotion_docs.tar emotion_docs.tar.gz
tar -cvf emotion_docs.tar doc/html doc/man doc/latex
gzip -9 emotion_docs.tar
exit 0
