"#ifdef GL_ES\n"
"precision highp float;\n"
"#endif\n"
"uniform sampler2D tex;\n"
"varying vec2 tex_c;\n"
"void main()\n"
"{\n"
"   float inten = dot(texture2D(tex,tex_c.xy).rgb,vec3(.3, .59, .11));\n"
"   gl_FragColor = vec4(inten, inten, inten, texture2D(tex,tex_c.xy).a);\n"
"}\n"
