"#ifdef GL_ES\n"
"#ifdef GL_FRAGMENT_PRECISION_HIGH\n"
"precision highp float;\n"
"#else\n"
"precision mediump float;\n"
"#endif\n"
"#endif\n"
"attribute vec4 vertex;\n"
"attribute vec4 color;\n"
"attribute vec2 tex_coord, tex_coord2;\n"
"uniform mat4 mvp;\n"
"varying vec2 tex_y, tex_cuv;\n"
"void main()\n"
"{\n"
"   gl_Position = mvp * vertex;\n"
"   tex_y = tex_coord;\n"
"   tex_cuv = tex_coord2 * 0.5;\n"
"}\n"
