"#ifdef GL_ES\n"
"precision mediump float;\n"
"#endif\n"
"uniform sampler2D tex, texu, texv;\n"
"varying vec4 col;\n"
"varying vec2 tex_c;\n"
"varying vec2 tex_c2;\n"
"varying vec2 tex_c3;\n"
"void main()\n"
"{\n"
"   float r, g, b, y, u, v;\n"
"   y = texture2D(tex, tex_c.xy).r;\n"
"   u = texture2D(texu, tex_c2.xy).r;\n"
"   v = texture2D(texv, tex_c3.xy).r;\n"
"   y = (y - 0.0625) * 1.164;\n"
"   u = u - 0.5;\n"
"   v = v - 0.5;\n"
"   r = y + (1.402   * v);\n"
"   g = y - (0.34414 * u) - (0.71414 * v);\n"
"   b = y + (1.772   * u);\n"
"   gl_FragColor = vec4(r, g, b, 1.0) * col;\n"
"}\n"
