#!/bin/sh
cp ./edje.c.in ./edje.c
for I in `find ./src/lib -name "edje.h" -print`; do
  cat $I >> ./edje.c
done
#for I in `find ./src/lib -name "*.c" -print`; do
#  cat $I >> ./edje.c
#done
rm -rf ./doc/html ./doc/latex ./doc/man
doxygen
cp doc/img/*.png doc/html/
rm -f edje_docs.tar edje_docs.tar.gz
tar -cvf edje_docs.tar doc/html doc/man doc/latex
gzip -9 edje_docs.tar
exit 0
