#ifndef _ELM_SYS_NOTIFY_DBUS_EO_LEGACY_H_
#define _ELM_SYS_NOTIFY_DBUS_EO_LEGACY_H_

#ifndef _ELM_SYS_NOTIFY_DBUS_EO_CLASS_TYPE
#define _ELM_SYS_NOTIFY_DBUS_EO_CLASS_TYPE

typedef Eo Elm_Sys_Notify_Dbus;

#endif

#ifndef _ELM_SYS_NOTIFY_DBUS_EO_TYPES
#define _ELM_SYS_NOTIFY_DBUS_EO_TYPES


#endif

#endif
