#ifndef _ELM_SLIDER_PART_INDICATOR_EO_LEGACY_H_
#define _ELM_SLIDER_PART_INDICATOR_EO_LEGACY_H_

#ifndef _ELM_SLIDER_PART_INDICATOR_EO_CLASS_TYPE
#define _ELM_SLIDER_PART_INDICATOR_EO_CLASS_TYPE

typedef Eo Elm_Slider_Part_Indicator;

#endif

#ifndef _ELM_SLIDER_PART_INDICATOR_EO_TYPES
#define _ELM_SLIDER_PART_INDICATOR_EO_TYPES


#endif



#endif
