#ifndef _ELM_CALENDAR_ITEM_EO_LEGACY_H_
#define _ELM_CALENDAR_ITEM_EO_LEGACY_H_

#ifndef _ELM_CALENDAR_ITEM_EO_CLASS_TYPE
#define _ELM_CALENDAR_ITEM_EO_CLASS_TYPE

typedef Eo Elm_Calendar_Item;

#endif

#ifndef _ELM_CALENDAR_ITEM_EO_TYPES
#define _ELM_CALENDAR_ITEM_EO_TYPES


#endif



#endif
