#ifndef _ELM_FILESELECTOR_BUTTON_EO_LEGACY_H_
#define _ELM_FILESELECTOR_BUTTON_EO_LEGACY_H_

#ifndef _ELM_FILESELECTOR_BUTTON_EO_CLASS_TYPE
#define _ELM_FILESELECTOR_BUTTON_EO_CLASS_TYPE

typedef Eo Elm_Fileselector_Button;

#endif

#ifndef _ELM_FILESELECTOR_BUTTON_EO_TYPES
#define _ELM_FILESELECTOR_BUTTON_EO_TYPES


#endif

#endif
