#ifndef _ELM_CODE_WIDGET_LEGACY_EO_LEGACY_H_
#define _ELM_CODE_WIDGET_LEGACY_EO_LEGACY_H_

#ifndef _ELM_CODE_WIDGET_LEGACY_EO_CLASS_TYPE
#define _ELM_CODE_WIDGET_LEGACY_EO_CLASS_TYPE

typedef Eo Elm_Code_Widget_Legacy;

#endif

#ifndef _ELM_CODE_WIDGET_LEGACY_EO_TYPES
#define _ELM_CODE_WIDGET_LEGACY_EO_TYPES


#endif

#endif
