#!/bin/sh
rm -rf ./doc/html ./doc/latex ./doc/man
mkdir -p ./doc/html ./doc/latex ./doc/man
doxygen
cp doc/img/*.png doc/html/
cp doc/img/*.gif doc/html/
rm -f embryo_docs.tar embryo_docs.tar.gz
tar -cvf embryo_docs.tar doc/html doc/man doc/latex
gzip -9 embryo_docs.tar
exit 0
