/* this table was taken from ecore_fb, is the default en layout */
         "0x00",          "0x00",          "0x00", /**/"",    "",    "",  NULL,/***/
       "Escape",        "Escape",        "Escape", /**/"\033","\033","\033","\033",/***/
            "1",        "exclam",             "1", /**/"1",   "!",   "1",  NULL,/***/
            "2",            "at",             "2", /**/"2",   "@",   "2",  "",/***/
            "3",    "numbersign",             "3", /**/"3",   "#",   "3",  "\x1b",/***/
            "4",        "dollar",             "4", /**/"4",   "$",   "4",  "\x1c",/***/
            "5",       "percent",             "5", /**/"5",   "%",   "5",  "\x1d",/***/
            "6",  "asciicircumm",             "6", /**/"6",   "^",   "6",  "\x1e",/***/
            "7",     "ampersand",             "7", /**/"7",   "&",   "7",  "\x1f",/***/
            "8",       "asterisk",            "8", /**/"8",   "*",   "8",  "\x7f",/***/
            "9",     "parenleft",             "9", /**/"9",   "(",   "9",  NULL,/***/
            "0",    "parenright",             "0", /**/"0",   ")",   "0",  NULL,/***/
        "minus",    "underscore",         "minus", /**/"-",   "_",   "-",  NULL,/***/
        "equal",          "plus",         "equal", /**/"=",   "+",   "=",  NULL,/***/
    "BackSpace",     "BackSpace",     "BackSpace", /**/"\010","\010","\010",  NULL,/***/
          "Tab",  "ISO_Left_Tab",           "Tab", /**/"\011","",    "\011",  NULL,/***/
            "q",             "Q",             "Q", /**/"q",   "Q",   "Q",  "\x11",/***/
            "w",             "W",             "W", /**/"w",   "W",   "W",  "\x17",/***/
            "e",             "E",             "E", /**/"e",   "E",   "E",  "\x05",/***/
            "r",             "R",             "R", /**/"r",   "R",   "R",  "\x12",/***/
            "t",             "T",             "T", /**/"t",   "T",   "T",  "\x14",/***/
            "y",             "Y",             "Y", /**/"y",   "Y",   "Y",  "\x19",/***/
            "u",             "U",             "U", /**/"u",   "U",   "U",  "\x15",/***/
            "i",             "I",             "I", /**/"i",   "I",   "I",  "\x09",/***/
            "o",             "O",             "O", /**/"o",   "O",   "O",  "\x0f",/***/
            "p",             "P",             "P", /**/"p",   "P",   "P",  "\x10",/***/
  "bracketleft",     "braceleft",   "bracketleft", /**/"[",   "{",   "[",  "\x1b",/***/
 "bracketright",    "braceright",  "bracketright", /**/"]",   "}",   "]",  "\x1d",/***/
       "Return",        "Return",        "Return", /**/"\015","\015","\015",  NULL,/***/
    "Control_L",     "Control_L",     "Control_L", /**/"",    "",    "",  NULL,/***/
            "a",             "A",             "A", /**/"a",   "A",   "A",  "\x01",/***/
            "s",             "S",             "S", /**/"s",   "S",   "S",  "\x13",/***/
            "d",             "D",             "D", /**/"d",   "D",   "D",  "\x04",/***/
            "f",             "F",             "F", /**/"f",   "F",   "F",  "\x06",/***/
            "g",             "G",             "G", /**/"g",   "G",   "G",  "\x07",/***/
            "h",             "h",             "H", /**/"h",   "H",   "H",  "\x08",/***/
            "j",             "J",             "J", /**/"j",   "J",   "J",  "\x0a",/***/
            "k",             "K",             "K", /**/"k",   "K",   "K",  "\x0b",/***/
            "l",             "L",             "L", /**/"l",   "L",   "L",  "\x0c",/***/
    "semicolon",         "colon",     "semicolon", /**/";",   ":",   ";",  NULL,/***/
   "apostrophe",      "quotedbl",    "apostrophe", /**/"'",   "\"",  "'",  NULL,/***/
        "grave",    "asciitilde",         "grave", /**/"`",   "~",   "`",  "",/***/
      "Shift_L",       "Shift_L",       "Shift_L", /**/"",    "",    "",  NULL,/***/
    "backslash",           "bar",     "backslash", /**/"\\",  "|",   "\\",  "\x1c",/***/
            "z",             "Z",             "Z", /**/"z",   "Z",   "Z",  "\x1a",/***/
            "x",             "X",             "X", /**/"x",   "X",   "X",  "\x18",/***/
            "c",             "C",             "C", /**/"c",   "C",   "C",  "\x03",/***/
            "v",             "V",             "V", /**/"v",   "V",   "V",  "\x16",/***/
            "b",             "B",             "B", /**/"b",   "B",   "B",  "\x02",/***/
            "n",             "N",             "N", /**/"n",   "N",   "N",  "\x0e",/***/
            "m",             "M",             "M", /**/"m",   "M",   "M",  "\x0d",/***/
        "comma",          "less",         "comma", /**/",",   "<",   ",",  NULL,/***/
       "period",       "greater",        "period", /**/".",   ">",   ".",  NULL,/***/
        "slash",      "question",         "slash", /**/"/",   "?",   "/",  "",/***/
      "Shift_R",       "Shift_R",       "Shift_R", /**/"",    "",    "",  NULL,/***/
  "KP_Multiply",   "KP_Multiply",   "KP_Multiply", /**/"",    "*",   "",  NULL,/***/
        "Alt_L",         "Alt_L",         "Alt_L", /**/"",    "",    "",  NULL,/***/
        "space",         "space",         "space", /**/" ",   " ",   " ",  "",/***/
    "Caps_Lock",     "Caps_Lock",     "Caps_Lock", /**/"",    "",    "",  NULL,/***/
           "F1",            "F1",            "F1", /**/"",    "",    "",  NULL,/***/
           "F2",            "F2",            "F2", /**/"",    "",    "",  NULL,/***/
           "F3",            "F3",            "F3", /**/"",    "",    "",  NULL,/***/
           "F4",            "F4",            "F4", /**/"",    "",    "",  NULL,/***/
           "F5",            "F5",            "F5", /**/"",    "",    "",  NULL,/***/
           "F6",            "F6",            "F6", /**/"",    "",    "",  NULL,/***/
           "F7",            "F7",            "F7", /**/"",    "",    "",  NULL,/***/
           "F8",            "F8",            "F8", /**/"",    "",    "",  NULL,/***/
           "F9",            "F9",            "F9", /**/"",    "",    "",  NULL,/***/
          "F10",           "F10",           "F10", /**/"",    "",    "",  NULL,/***/
     "Num_Lock",      "Num_Lock",      "Num_Lock", /**/"",    "",    "",  NULL,/***/
  "Scroll_Lock",   "Scroll_Lock",   "Scroll_Lock", /**/"",    "",    "",  NULL,/***/
      "KP_Home",          "KP_7",       "KP_Home", /**/"",    "7",   "",  NULL,/***/
        "KP_Up",          "KP_8",         "KP_Up", /**/"",    "8",   "",  NULL,/***/
     "KP_Prior",          "KP_9",      "KP_Prior", /**/"",    "9",   "",  NULL,/***/
  "KP_Subtract",   "KP_Subtract",   "KP_Subtract", /**/"",    "",    "",  NULL,/***/
      "KP_Left",          "KP_4",       "KP_Left", /**/"",    "4",   "",  NULL,/***/
     "KP_Begin",          "KP_5",      "KP_Begin", /**/"",    "5",   "",  NULL,/***/
     "KP_Right",          "KP_6",      "KP_Right", /**/"",    "6",   "",  NULL,/***/
       "KP_Add",        "KP_Add",        "KP_Add", /**/"",    "",    "",  NULL,/***/
       "KP_End",          "KP_1",        "KP_End", /**/"",    "1",   "",  NULL,/***/
      "KP_Down",          "KP_2",       "KP_Down", /**/"",    "2",   "",  NULL,/***/
      "KP_Next",          "KP_3",       "KP_Next", /**/"",    "3",   "",  NULL,/***/
    "KP_Insert",          "KP_0",     "KP_Insert", /**/"",    "0",   "",  NULL,/***/
    "KP_Delete",    "KP_Decimal",     "KP_Delete", /**/"",    ".",   "",  NULL,/***/
         "0x54",          "0x54",          "0x54", /**/"",    "",    "",  NULL,/***/
         "0x55",          "0x55",          "0x55", /**/"",    "",    "",  NULL,/***/
         "0x56",          "0x56",          "0x56", /**/"",    "",    "",  NULL,/***/
          "F11",           "F11",           "F11", /**/"",    "",    "",  NULL,/***/
          "F12",           "F12",           "F12", /**/"",    "",    "",  NULL,/***/
         "0x59",          "0x59",          "0x59", /**/"",    "",    "",  NULL,/***/
         "0x5a",          "0x5a",          "0x5a", /**/"",    "",    "",  NULL,/***/
         "0x5b",          "0x5b",          "0x5b", /**/"",    "",    "",  NULL,/***/
         "0x5c",          "0x5c",          "0x5c", /**/"",    "",    "",  NULL,/***/
         "0x5d",          "0x5d",          "0x5d", /**/"",    "",    "",  NULL,/***/
         "0x5e",          "0x5e",          "0x5e", /**/"",    "",    "",  NULL,/***/
         "0x5f",          "0x5f",          "0x5f", /**/"",    "",    "",  NULL,/***/
     "KP_Enter",      "KP_Enter",      "KP_Enter", /**/"\015", "\015", "\015",  NULL,/***/
    "Control_R",     "Control_R",     "Control_R", /**/"",    "",    "",  NULL,/***/
    "KP_Divide",     "KP_Divide",     "KP_Divide", /**/"",    "",    "",  NULL,/***/
        "Print",         "Print",         "Print", /**/"",    "",    "",  NULL,/***/
        "Alt_R",         "Alt_R",         "Alt_R", /**/"",    "",    "",  NULL,/***/
         "0x65",          "0x65",          "0x65", /**/"",    "",    "",  NULL,/***/
         "Home",          "Home",          "Home", /**/"",    "",    "",  NULL,/***/
           "Up",            "Up",            "Up", /**/"",    "",    "",  NULL,/***/
        "Prior",         "Prior",         "Prior", /**/"",    "",    "",  NULL,/***/
         "Left",          "Left",          "Left", /**/"",    "",    "",  NULL,/***/
        "Right",         "Right",         "Right", /**/"",    "",    "",  NULL,/***/
          "End",           "End",           "End", /**/"",    "",    "",  NULL,/***/
         "Down",          "Down",          "Down", /**/"",    "",    "",  NULL,/***/
         "Next",          "Next",          "Next", /**/"",    "",    "",  NULL,/***/
       "Insert",        "Insert",        "Insert", /**/"",    "",    "",  NULL,/***/
       "Delete",        "Delete",        "Delete", /**/"\177","\177","\177",  NULL,/***/
         "0x70",          "0x70",          "0x70", /**/"",    "",    "",  NULL,/***/
         "0x71",          "0x71",          "0x71", /**/"",    "",    "",  NULL,/***/
         "0x72",          "0x72",          "0x72", /**/"",    "",    "",  NULL,/***/
         "0x73",          "0x73",          "0x73", /**/"",    "",    "",  NULL,/***/
         "0x74",          "0x74",          "0x74", /**/"",    "",    "",  NULL,/***/
         "0x75",          "0x75",          "0x75", /**/"",    "",    "",  NULL,/***/
         "0x76",          "0x76",          "0x76", /**/"",    "",    "",  NULL,/***/
        "Pause",         "Pause",         "Pause", /**/"",    "",    "",  NULL,/***/
         "0x78",          "0x78",          "0x78", /**/"",    "",    "",  NULL,/***/
         "0x79",          "0x79",          "0x79", /**/"",    "",    "",  NULL,/***/
         "0x7a",          "0x7a",          "0x7a", /**/"",    "",    "",  NULL,/***/
         "0x7b",          "0x7b",          "0x7b", /**/"",    "",    "",  NULL,/***/
         "0x7c",          "0x7c",          "0x7c", /**/"",    "",    "",  NULL,/***/
      "Super_L",       "Super_L",       "Super_L", /**/"",    "",    "",  NULL,/***/
      "Super_R",       "Super_R",       "Super_R", /**/"",    "",    "",  NULL,/***/
         "0x7f",          "0x7f",          "0x7f", /**/"",    "",    "",  NULL, /***/
