.\"                                      Hey, EMACS: -*- nroff -*-
.TH EET 1 "oktober  3, 2002"
.SH NAME
eet-config \- script to get information about the installed version of Eet
.SH SYNOPSIS
.B eet-config [\-\-version] [\-\-libs] [\-\-cflags]
.SH DESCRIPTION
\fIeet-config\fP is a tool that is used by configure to determine the
availability of eet and the compiler and linker flags that should be used to
compile programs using it.
.SH OPTIONS
\fIeet-config\fP accepts the following options:
.TP
.B \-\-version
Print the currently installed version of \fIeet\fP on the standard output.
.TP
.B \-\-libs
Print the linker flags that are necessary to link a \fIeet\fP\-program.
.TP
.B \-\-cflags
Print the compiler flags that are necessary to link a \fIeet\fP\-program.
.SH SEE ALSO
.BR eet (1).
.SH AUTHOR
This manual page was written by Sytse Wielinga
<s.b.wielinga@student.utwente.nl> for the Debian GNU/Linux system (but may be
used by others).
