.TH EET 1 "November 4, 2007" eet
.SH NAME
eet \- Small tool to handle eet files.
.SH SYNOPSIS
.B eet
.RI -l " FILE.EET"
.br
.B eet
.RI -r " FILE.EET KEY"
.br
.B eet
.RI "-x|-d" " FILE.EET KEY OUT-FILE"
.br
.B eet
.RI "-i|-e" " FILE.EET KEY IN-FILE COMPRESS"
.br
.SH DESCRIPTION
This manual page documents briefly the
.B eet
command
.PP
\fBeet\fP is a program that can extract, import, delete, list, decode and encode data from eet files.
.SH OPTIONS
.TP
.B \-l
List all keys in FILE.EET.
.TP
.B \-r
Remove KEY in FILE.EET.
.TP
.B \-x
Extract data stored in KEY in FILE.EET and write to OUT-FILE
.TP
.B \-d
Extract and decode data stored in KEY in FILE.EET and write to OUT-FILE
.TP
.B \-i
Insert data to KEY in FILE.EET from IN-FILE and if COMPRESS is 1, compress it
.TP
.B \-e
Insert and encode to KEY in FILE.EET from IN-FILE and if COMPRESS is 1, compress it
.SH BUGS
To report a bug, please visit \fIhttp://bugs.enlightenment.org/\fR
.SH AUTHOR
.TP
eet was written by the Enlightenment Development Team
.I http://web.enlightenment.org
.PP
This manual page was written by Albin Tonnerre <albin.tonnerre@gmail.com>,
for the Debian project (but may be used by others).
