.\"                                      Hey, EMACS: -*- nroff -*-
.TH EET 1 "oktober  3, 2002"
.SH NAME
eet \- program for editing eet files
.SH SYNOPSIS
.B eet
-l in_file
.br
.B eet
-d in_file
.br
.B eet
-c out_file [-nz glob [-nz glob ...]] dir_file1 [dir_file2 ...]
.SH DESCRIPTION
This manual page documents briefly the
.B eet
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
.B eet
is a program for viewing, unpacking and adding files to eet files, which are
containers for optionally compressed data, allowing for fast random-access
reading. These files are mostly used by the enlightenment project. See
.B www.enlightenment.org
for more details about this project.
.SH OPTIONS
.TP
.B \-l in_file
List the contents of an eet file
.TP
.B \-d in_file
Unpack an eet file
.TP
.B \-c out_file
Create an eet file
.TP
.B \-nz match
Store files matching match glob uncompressed
.SH SEE ALSO
.BR eet-config (1).
.PP
For more information, have a look at the sources of libeet. To get them, have
a look at the website
.B www.enlightenment.org
or execute the following commands:
.TP
.B export CVSROOT=:pserver:anonymous@cvs.enlightenment.sourceforge.net:/cvsroot/enlightenment
If this is command is broken among multiple lines because your terminal is not
as wide as the command, please don't include the minus sign into the command.
.TP
.B cvs login
Just hit enter if it asks about a password for anonymous.
.TP
.B cvs co -r SPLIT e17/libs/eet
This command should create the directory e17/libs/eet, containing the latest
sources of eet.
.SH AUTHOR
This manual page was written by Sytse Wielinga
<s.b.wielinga@student.utwente.nl> for the Debian GNU/Linux system (but may be
used by others).
