#define ELM_ATSPI_CLASS elm_atspi_obj_class_get()

const Eo_Class *elm_atspi_obj_class_get(void) EINA_CONST;

extern EAPI Eo_Op ELM_ATSPI_OBJ_BASE_ID;

enum
{
   ELM_ATSPI_OBJ_SUB_ID_NAME_GET,
   ELM_ATSPI_OBJ_SUB_ID_NAME_SET,
   ELM_ATSPI_OBJ_SUB_ID_DESCRIPTION_GET,
   ELM_ATSPI_OBJ_SUB_ID_DESCRIPTION_SET,
   ELM_ATSPI_OBJ_SUB_ID_PARENT_GET,
   ELM_ATSPI_OBJ_SUB_ID_CHILD_AT_INDEX_GET,
   ELM_ATSPI_OBJ_SUB_ID_CHILDREN_GET,
   ELM_ATSPI_OBJ_SUB_ID_INDEX_IN_PARENT_GET,
   ELM_ATSPI_OBJ_SUB_ID_RELATION_SET_GET,
   ELM_ATSPI_OBJ_SUB_ID_RELATION_SET_SET,
   ELM_ATSPI_OBJ_SUB_ID_ROLE_GET,
   ELM_ATSPI_OBJ_SUB_ID_ROLE_SET,
   ELM_ATSPI_OBJ_SUB_ID_ROLE_NAME_GET,
   ELM_ATSPI_OBJ_SUB_ID_LOCALIZED_ROLE_NAME_GET,
   ELM_ATSPI_OBJ_SUB_ID_STATE_GET,
   ELM_ATSPI_OBJ_SUB_ID_ATTRIBUTES_GET,
   ELM_ATSPI_OBJ_SUB_ID_LAST
};

#define ELM_ATSPI_OBJ_ID(sub_id) (ELM_ATSPI_OBJ_BASE_ID + sub_id)

/* Component Interface */
#define ELM_ATSPI_COMPONENT_INTERFACE elm_atspi_component_interface_get()

const Eo_Class *elm_atspi_component_interface_get(void) EINA_CONST;

extern EAPI Eo_Op ELM_ATSPI_COMPONENT_INTERFACE_BASE_ID;

enum
{
   ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_CONTAINS,
   ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_ACCESSIBLE_AT_POINT_GET,
   ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_EXTENTS_GET,
   ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_EXTENTS_SET,
   ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_POSITION_GET,
   ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_POSITION_SET,
   ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_SIZE_GET,
   ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_SIZE_SET,
   ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_LAYER_GET,
   ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_Z_ORDER_GET,
   ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_FOCUS_GRAB,
   ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_ALPHA_GET,
   ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_LAST
};

#define ELM_ATSPI_COMPONENT_INTERFACE_ID(sub_id) (ELM_ATSPI_COMPONENT_INTERFACE_BASE_ID + sub_id)
/* Component Interface - END */

/* Action Interface */
#define ELM_ATSPI_ACTION_INTERFACE elm_accessible_action_interface_get()

const Eo_Class *elm_accessible_action_interface_get(void) EINA_CONST;

extern EAPI Eo_Op ELM_ATSPI_ACTION_INTERFACE_BASE_ID;

enum
{
   ELM_ATSPI_ACTION_INTERFACE_SUB_ID_ACTION_COUNT,
   ELM_ATSPI_ACTION_INTERFACE_SUB_ID_ACTION_DO,
   ELM_ATSPI_ACTION_INTERFACE_SUB_ID_DESCRIPTION_GET,
   ELM_ATSPI_ACTION_INTERFACE_SUB_ID_NAME_GET,
   ELM_ATSPI_ACTION_INTERFACE_SUB_ID_LOCALIZED_NAME_GET,
   ELM_ATSPI_ACTION_INTERFACE_SUB_ID_KEY_BINDING_GET,
   ELM_ATSPI_ACTION_INTERFACE_SUB_ID_LAST
};
/* Action Interface - END */

/* Text Interface */
#define ELM_ATSPI_TEXT_INTERFACE elm_accessible_text_interface_get()

const Eo_Class *elm_accessible_text_interface_get(void) EINA_CONST;

extern EAPI Eo_Op ELM_ATSPI_TEXT_INTERFACE_BASE_ID;

enum
{
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_CHARACTER_COUNT,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_CARET_OFFSET_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_CARET_OFFSET_SET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_TEXT_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_TEXT_BEFORE_OFFSET_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_TEXT_AT_OFFSET_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_TEXT_AFTER_OFFSET_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_CHARACTER_AT_OFFSET_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_ATTRIBUTE_VALUE_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_ATTRIBUTES_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_DEFAULT_ATTRIBUTES_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_CHARACTER_EXTENTS_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_OFFSET_AT_POINT_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_SELECTIONS_COUNT,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_SELECTION_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_SELECTION_ADD,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_SELECTION_REMOVE,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_SELECTION_SET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_RANGE_EXTENTS_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_BAOUNDED_RANGES_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_ATTRIBUTE_RUN_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_DEFAULT_ATTRIBUTE_SET_GET,
   ELM_ATSPI_TEXT_INTERFACE_SUB_ID_LAST
};
/* Text Interface - END */

/* EditableText Interface */
#define ELM_ATSPI_EDITABLE_TEXT_INTERFACE elm_accessible_editable_text_interface_get()

const Eo_Class *elm_accessible_editable_text_interface_get(void) EINA_CONST;

extern EAPI Eo_Op ELM_ATSPI_EDITABLE_TEXT_INTERFACE_BASE_ID;

enum
{
   ELM_ATSPI_EDITABLE_TEXT_INTERFACE_SUB_ID_TEXT_CONTENTS_SET,
   ELM_ATSPI_EDITABLE_TEXT_INTERFACE_SUB_ID_TEXT_INSERT,
   ELM_ATSPI_EDITABLE_TEXT_INTERFACE_SUB_ID_TEXT_COPY,
   ELM_ATSPI_EDITABLE_TEXT_INTERFACE_SUB_ID_TEXT_CUT,
   ELM_ATSPI_EDITABLE_TEXT_INTERFACE_SUB_ID_TEXT_DELETE,
   ELM_ATSPI_EDITABLE_TEXT_INTERFACE_SUB_ID_TEXT_PASTE,
   ELM_ATSPI_EDITABLE_TEXT_INTERFACE_SUB_ID_LAST
};
/* EditableText Interface - END */

#define ELM_ATSPI_VALUE_INTERFACE elm_accessible_value_interface_get()


/* Value Interface */
const Eo_Class *elm_accessible_value_interface_get(void) EINA_CONST;

extern EAPI Eo_Op ELM_ATSPI_VALUE_INTERFACE_BASE_ID;

enum
{
   ELM_ATSPI_VALUE_INTERFACE_SUB_ID_MINIMUM_GET,
   ELM_ATSPI_VALUE_INTERFACE_SUB_ID_MAXIMUM_GET,
   ELM_ATSPI_VALUE_INTERFACE_SUB_ID_MINIMUM_INCREMENT_GET,
   ELM_ATSPI_VALUE_INTERFACE_SUB_ID_VALUE_GET,
   ELM_ATSPI_VALUE_INTERFACE_SUB_ID_VALUE_SET,
   ELM_ATSPI_VALUE_INTERFACE_SUB_ID_LAST
};
/* Value Interface - END */


/* Image Interface */
const Eo_Class *elm_accessible_image_interface_get(void) EINA_CONST;

extern EAPI Eo_Op ELM_ATSPI_IMAGE_INTERFACE_BASE_ID;

enum
{
   ELM_ATSPI_IMAGE_INTERFACE_SUB_ID_IMAGE_DESCRIPTION_GET,
   ELM_ATSPI_IMAGE_INTERFACE_SUB_ID_IMAGE_LOCALE_GET,
   ELM_ATSPI_IMAGE_INTERFACE_SUB_ID_IMAGE_EXTENTS_GET,
   ELM_ATSPI_IMAGE_INTERFACE_SUB_ID_IMAGE_POSITION_GET,
   ELM_ATSPI_IMAGE_INTERFACE_SUB_ID_IMAGE_SIZE_GET,
   ELM_ATSPI_IMAGE_INTERFACE_SUB_ID_LAST
};
/* Image Interface - END */

/* Selection Interface */
const Eo_Class *elm_accessible_selection_interface_get(void) EINA_CONST;

extern EAPI Eo_Op ELM_ATSPI_SELECTION_INTERFACE_BASE_ID;

enum
{
   ELM_ATSPI_SELECTION_INTERFACE_SUB_ID_SELECTED_CHILDREN_COUNT,
   ELM_ATSPI_SELECTION_INTERFACE_SUB_ID_SELECTED_CHILD_GET,
   ELM_ATSPI_SELECTION_INTERFACE_SUB_ID_CHILD_SELECT,
   ELM_ATSPI_SELECTION_INTERFACE_SUB_ID_CHILD_DESELECT,
   ELM_ATSPI_SELECTION_INTERFACE_SUB_ID_SELECT_ALL,
   ELM_ATSPI_SELECTION_INTERFACE_SUB_ID_SELECTION_CLEAR,
   ELM_ATSPI_SELECTION_INTERFACE_SUB_ID_LAST
};
/* Selection Interface - END */

#define elm_atspi_obj_name_get(ret)\
   ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_NAME_GET), \
   EO_TYPECHECK(const char **, ret)

#define elm_atspi_obj_name_set(name)\
   ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_NAME_SET),\
   EO_TYPECHECK(const char *, name)

#define elm_atspi_obj_role_get(role)\
   ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_ROLE_GET), \
   EO_TYPECHECK(AtspiRole*, role)

#define elm_atspi_obj_role_set(role)\
   ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_ROLE_SET),\
   EO_TYPECHECK(AtspiRole, role)

#define elm_atspi_obj_role_name_get(ret)\
   ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_ROLE_NAME_GET),\
   EO_TYPECHECK(const char **, ret)

#define elm_atspi_obj_localized_role_name_get(ret)\
   ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_LOCALIZED_ROLE_NAME_GET),\
   EO_TYPECHECK(const char **, ret)

#define elm_atspi_obj_description_get(ret)\
   ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_DESCRIPTION_GET),\
   EO_TYPECHECK(const char **, ret)

#define elm_atspi_obj_description_set(desc)\
   ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_DESCRIPTION_SET),\
   EO_TYPECHECK(const char *, desc)

#define elm_atspi_obj_parent_get(ret)\
   ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_PARENT_GET),\
   EO_TYPECHECK(Elm_Atspi_Object**, ret)

#define elm_atspi_obj_child_at_index_get(idx, ret)\
   ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_CHILD_AT_INDEX_GET), \
   EO_TYPECHECK(int, idx),\
   EO_TYPECHECK(Elm_Atspi_Object**, ret)

#define elm_atspi_obj_children_get(ret)\
   ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_CHILDREN_GET),\
   EO_TYPECHECK(Eina_List**, ret)

#define elm_atspi_obj_index_in_parent_get(ret)\
   ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_INDEX_IN_PARENT_GET),\
   EO_TYPECHECK(int*, ret)

#define elm_atspi_obj_relation_set_get()\
   ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_RELATION_SET_GET),\
   EO_TYPECHECK()

#define elm_atspi_obj_relation_set_set() ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_RELATION_SET_SET), EO_TYPECHECK()

#define elm_atspi_obj_state_get() ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_STATE_GET), EO_TYPECHECK()

#define elm_atspi_obj_attributes_get() ELM_ATSPI_OBJ_ID(ELM_ATSPI_OBJ_SUB_ID_ATTRIBUTES_GET), EO_TYPECHECK()

#define elm_atspi_component_interface_contains(x, y, type, ret)\
   ELM_ATSPI_COMPONENT_INTERFACE_ID(ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_CONTAINS),\
   EO_TYPECHECK(int, x),\
   EO_TYPECHECK(int, y),\
   EO_TYPECHECK(AtspiCoordType, type),\
   EO_TYPECHECK(Eina_Bool*, ret)

#define elm_atspi_component_interface_accessible_at_point_get(x, y, type, ret)\
   ELM_ATSPI_COMPONENT_INTERFACE_ID(ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_ACCESSIBLE_AT_POINT_GET),\
   EO_TYPECHECK(int, x),\
   EO_TYPECHECK(int, y),\
   EO_TYPECHECK(AtspiCoordType, type),\
   EO_TYPECHECK(Elm_Atspi_Object**, ret)

#define elm_atspi_component_interface_extents_get(x, y, w, h, type)\
   ELM_ATSPI_COMPONENT_INTERFACE_ID(ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_EXTENTS_GET),\
   EO_TYPECHECK(int*, x),\
   EO_TYPECHECK(int*, y),\
   EO_TYPECHECK(int*, w),\
   EO_TYPECHECK(int*, h), \
   EO_TYPECHECK(AtspiCoordType, type)

#define elm_atspi_component_interface_extents_set(x, y, w, h, type, ret)\
   ELM_ATSPI_COMPONENT_INTERFACE_ID(ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_EXTENTS_SET),\
   EO_TYPECHECK(int, x),\
   EO_TYPECHECK(int, y),\
   EO_TYPECHECK(int, w),\
   EO_TYPECHECK(int, h),\
   EO_TYPECHECK(AtspiCoordType, type),\
   EO_TYPECHECK(Eina_Bool*, ret)

#define elm_atspi_component_interface_position_get(x, y, type)\
   ELM_ATSPI_COMPONENT_INTERFACE_ID(ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_POSITION_GET),\
   EO_TYPECHECK(int*, x),\
   EO_TYPECHECK(int*, y), \
   EO_TYPECHECK(AtspiCoordType, type)

#define elm_atspi_component_interface_position_set(x, y, type, ret)\
   ELM_ATSPI_COMPONENT_INTERFACE_ID(ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_POSITION_SET),\
   EO_TYPECHECK(int, x),\
   EO_TYPECHECK(int, y),\
   EO_TYPECHECK(AtspiCoordType, type),\
   EO_TYPECHECK(Eina_Bool*, ret)

#define elm_atspi_component_interface_size_get(x, y)\
   ELM_ATSPI_COMPONENT_INTERFACE_ID(ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_SIZE_GET),\
   EO_TYPECHECK(int*, x),\
   EO_TYPECHECK(int*, y)

#define elm_atspi_component_interface_size_set(x, y, ret)\
   ELM_ATSPI_COMPONENT_INTERFACE_ID(ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_SIZE_SET),\
   EO_TYPECHECK(int, x),\
   EO_TYPECHECK(int, y),\
   EO_TYPECHECK(Eina_Bool*, ret)

#define elm_atspi_component_interface_layer_get(ret)\
   ELM_ATSPI_COMPONENT_INTERFACE_ID(ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_LAYER_GET),\
   EO_TYPECHECK(int*, ret)

#define elm_atspi_component_interface_z_order_get(ret)\
   ELM_ATSPI_COMPONENT_INTERFACE_ID(ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_Z_ORDER_GET),\
   EO_TYPECHECK(int*, ret)

#define elm_atspi_component_interface_focus_grab(ret)\
   ELM_ATSPI_COMPONENT_INTERFACE_ID(ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_FOCUS_GRAB),\
   EO_TYPECHECK(Eina_Bool*, ret)

#define elm_atspi_component_interface_alpha_get(ret)\
   ELM_ATSPI_COMPONENT_INTERFACE_ID(ELM_ATSPI_COMPONENT_INTERFACE_SUB_ID_ALPHA_GET),\
   EO_TYPECHECK(double*, ret)
