[Icon Theme]
Name=Bluish-X
Inherits=hicolor
Comment=The EFL Bluish-X Icon theme. Orig. Based on Rave-X and Mint-X Icon Themes.
Directories=places/scalable,places/16,emblems/scalable
Example=directory-x-normal

[places/scalable]
Size=128
Context=Places
Type=Scalable
MinSize=23

[places/16]
Size=16
Context=Places
Type=Scalable
MinSize=16
MaxSize=22

[emblems/scalable]
Size=96
Context=Emblems
Type=Scalable
