#!/bin/sh
cp ./eet.c.in ./eet.c
for I in `find ./src/lib -name "Eet.h" -print`; do
  cat $I >> ./eet.c
done
#for I in `find ./src/lib -name "*.c" -print`; do
#  cat $I >> ./eet.c
#done
rm -rf ./doc/html ./doc/latex ./doc/man
doxygen
cp doc/img/* doc/html/
rm -f eet_docs.tar eet_docs.tar.gz
tar -cvf eet_docs.tar doc/html doc/man doc/latex
gzip -9 eet_docs.tar
exit 0
