#!/bin/sh
cp ./evas.c.in ./evas.c
cat ./src/lib/Evas.h >> ./evas.c
for I in `find ./src/lib -name "*.c" -print`; do
  cat $I >> ./evas.c
done
rm -rf ./doc/html ./doc/latex ./doc/man
doxygen
cp doc/img/*.png doc/html/
exit 0
