CC=gcc
COMMON_FLAGS=`pkg-config --libs --cflags eina,ecore,eldbus,elocation`

EXAMPLES= elocation

all: examples
examples: $(EXAMPLES)

$(EXAMPLES):
	$(CC) -o $@ $@.c $(COMMON_FLAGS)

clean:
	@echo "Cleaning up built objects..."
	@rm -Rf $(EXAMPLES)
