_EVASGL_FUNCTION_BEGIN_VOID( glAlphaFunc, GLenum, func, GLclampf, ref )
_EVASGL_FUNCTION_BEGIN_VOID( glClearDepthf, GLclampf, depth )
_EVASGL_FUNCTION_BEGIN_VOID( glClipPlanef, GLenum, plane, const GLfloat *, equation )
_EVASGL_FUNCTION_BEGIN_VOID( glColor4f, GLfloat, red, GLfloat, green, GLfloat, blue, GLfloat, alpha )
_EVASGL_FUNCTION_BEGIN_VOID( glDepthRangef, GLclampf, zNear, GLclampf, zFar )
_EVASGL_FUNCTION_BEGIN_VOID( glFogf, GLenum, pname, GLfloat, param )
_EVASGL_FUNCTION_BEGIN_VOID( glFogfv, GLenum, pname, const GLfloat *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glFrustumf, GLfloat, left, GLfloat, right, GLfloat, bottom, GLfloat, top, GLfloat, zNear, GLfloat, zFar )
_EVASGL_FUNCTION_BEGIN_VOID( glGetClipPlanef, GLenum, pname, GLfloat *, eqn)
_EVASGL_FUNCTION_BEGIN_VOID( glGetFloatv, GLenum, pname, GLfloat *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glGetLightfv, GLenum, light, GLenum, pname, GLfloat *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glGetMaterialfv, GLenum, face, GLenum, pname, GLfloat *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glGetTexEnvfv, GLenum, env, GLenum, pname, GLfloat *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glGetTexParameterfv, GLenum, target, GLenum, pname, GLfloat *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glLightModelf, GLenum, pname, GLfloat, param )
_EVASGL_FUNCTION_BEGIN_VOID( glLightModelfv, GLenum, pname, const GLfloat *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glLightf, GLenum, light, GLenum, pname, GLfloat, param )
_EVASGL_FUNCTION_BEGIN_VOID( glLightfv, GLenum, light, GLenum, pname, const GLfloat *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glLineWidth, GLfloat, width )
_EVASGL_FUNCTION_BEGIN_VOID( glLoadMatrixf, const GLfloat *, m )
_EVASGL_FUNCTION_BEGIN_VOID( glMaterialf, GLenum, face, GLenum, pname, GLfloat, param )
_EVASGL_FUNCTION_BEGIN_VOID( glMaterialfv, GLenum, face, GLenum, pname, const GLfloat *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glMultMatrixf, const GLfloat *, m )
_EVASGL_FUNCTION_BEGIN_VOID( glMultiTexCoord4f, GLenum, target, GLfloat, s, GLfloat, t, GLfloat, r, GLfloat, q )
_EVASGL_FUNCTION_BEGIN_VOID( glNormal3f, GLfloat, nx, GLfloat, ny, GLfloat, nz )
_EVASGL_FUNCTION_BEGIN_VOID( glOrthof, GLfloat, left, GLfloat, right, GLfloat, bottom, GLfloat, top, GLfloat, zNear, GLfloat, zFar )
_EVASGL_FUNCTION_BEGIN_VOID( glPointParameterf, GLenum, pname, GLfloat, param )
_EVASGL_FUNCTION_BEGIN_VOID( glPointParameterfv, GLenum, pname, const GLfloat *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glPointSize, GLfloat, size )
_EVASGL_FUNCTION_BEGIN_VOID( glPointSizePointerOES, GLenum, type, GLsizei, stride, const GLvoid *, pointer )
_EVASGL_FUNCTION_BEGIN_VOID( glPolygonOffset, GLfloat, factor, GLfloat, units )
_EVASGL_FUNCTION_BEGIN_VOID( glRotatef, GLfloat, angle, GLfloat, x, GLfloat, y, GLfloat, z )
_EVASGL_FUNCTION_BEGIN_VOID( glScalef, GLfloat, x, GLfloat, y, GLfloat, z )
_EVASGL_FUNCTION_BEGIN_VOID( glTexEnvf, GLenum, target, GLenum, pname, GLfloat, param )
_EVASGL_FUNCTION_BEGIN_VOID( glTexEnvfv, GLenum, target, GLenum, pname, const GLfloat *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glTexParameterf, GLenum, target, GLenum, pname, GLfloat, param )
_EVASGL_FUNCTION_BEGIN_VOID( glTexParameterfv, GLenum, target, GLenum, pname, const GLfloat *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glTranslatef, GLfloat, x, GLfloat, y, GLfloat, z )
_EVASGL_FUNCTION_BEGIN_VOID( glActiveTexture, GLenum, texture )
_EVASGL_FUNCTION_BEGIN_VOID( glAlphaFuncx, GLenum, func, GLclampx, ref )
_EVASGL_FUNCTION_BEGIN_VOID( glBindBuffer, GLenum, target, GLuint, buffer )
_EVASGL_FUNCTION_BEGIN_VOID( glBindTexture, GLenum, target, GLuint, texture )
_EVASGL_FUNCTION_BEGIN_VOID( glBlendFunc, GLenum, sfactor, GLenum, dfactor )
_EVASGL_FUNCTION_BEGIN_VOID( glBufferData, GLenum, target, GLsizeiptr, size, const GLvoid *, data, GLenum, usage )
_EVASGL_FUNCTION_BEGIN_VOID( glBufferSubData, GLenum, target, GLintptr, offset, GLsizeiptr, size, const GLvoid *, data )
_EVASGL_FUNCTION_BEGIN_VOID( glClearColorx, GLclampx, red, GLclampx, green, GLclampx, blue, GLclampx, alpha )
_EVASGL_FUNCTION_BEGIN_VOID( glClearDepthx, GLclampx, depth )
_EVASGL_FUNCTION_BEGIN_VOID( glClearStencil, GLint, s )
_EVASGL_FUNCTION_BEGIN_VOID( glClientActiveTexture, GLenum, texture )
_EVASGL_FUNCTION_BEGIN_VOID( glClipPlanex, GLenum, plane, const GLfixed *, equation )
_EVASGL_FUNCTION_BEGIN_VOID( glColor4ub, GLubyte, red, GLubyte, green, GLubyte, blue, GLubyte, alpha )
_EVASGL_FUNCTION_BEGIN_VOID( glColor4x, GLfixed, red, GLfixed, green, GLfixed, blue, GLfixed, alpha )
_EVASGL_FUNCTION_BEGIN_VOID( glColorMask, GLboolean, red, GLboolean, green, GLboolean, blue, GLboolean, alpha )
_EVASGL_FUNCTION_BEGIN_VOID( glColorPointer, GLint, size, GLenum, type, GLsizei, stride, const GLvoid *, pointer )
_EVASGL_FUNCTION_BEGIN_VOID( glCompressedTexImage2D, GLenum, target, GLint, level, GLenum, internalformat, GLsizei, width, GLsizei, height, GLint, border, GLsizei, imageSize, const GLvoid *, data )
_EVASGL_FUNCTION_BEGIN_VOID( glCompressedTexSubImage2D, GLenum, target, GLint, level, GLint, xoffset, GLint, yoffset, GLsizei, width, GLsizei, height, GLenum, format, GLsizei, imageSize, const GLvoid *, data )
_EVASGL_FUNCTION_BEGIN_VOID( glCopyTexImage2D, GLenum, target, GLint, level, GLenum, internalformat, GLint, x, GLint, y, GLsizei, width, GLsizei, height, GLint, border )
_EVASGL_FUNCTION_BEGIN_VOID( glCopyTexSubImage2D, GLenum, target, GLint, level, GLint, xoffset, GLint, yoffset, GLint, x, GLint, y, GLsizei, width, GLsizei, height )
_EVASGL_FUNCTION_BEGIN_VOID( glCullFace, GLenum, mode )
_EVASGL_FUNCTION_BEGIN_VOID( glDeleteBuffers, GLsizei, n, const GLuint *, buffers )
_EVASGL_FUNCTION_BEGIN_VOID( glDeleteTextures, GLsizei, n, const GLuint *, textures )
_EVASGL_FUNCTION_BEGIN_VOID( glDepthFunc, GLenum, func )
_EVASGL_FUNCTION_BEGIN_VOID( glDepthMask, GLboolean, flag )
_EVASGL_FUNCTION_BEGIN_VOID( glDepthRangex, GLclampx, zNear, GLclampx, zFar )
_EVASGL_FUNCTION_BEGIN_VOID( glDisableClientState, GLenum, array )
_EVASGL_FUNCTION_BEGIN_VOID( glDrawArrays, GLenum, mode, GLint, first, GLsizei, count )
_EVASGL_FUNCTION_BEGIN_VOID( glDrawElements, GLenum, mode, GLsizei, count, GLenum, type, const GLvoid *, indices )
_EVASGL_FUNCTION_BEGIN_VOID( glEnableClientState, GLenum, array )
_EVASGL_FUNCTION_BEGIN_VOID( glFinish )
_EVASGL_FUNCTION_BEGIN_VOID( glFlush )
_EVASGL_FUNCTION_BEGIN_VOID( glFogx, GLenum, pname, GLfixed, param )
_EVASGL_FUNCTION_BEGIN_VOID( glFogxv, GLenum, pname, const GLfixed *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glFrontFace, GLenum, mode )
_EVASGL_FUNCTION_BEGIN_VOID( glFrustumx, GLfixed, left, GLfixed, right, GLfixed, bottom, GLfixed, top, GLfixed, zNear, GLfixed, zFar )
_EVASGL_FUNCTION_BEGIN_VOID( glGetBooleanv, GLenum, pname, GLboolean *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glGetBufferParameteriv, GLenum, target, GLenum, pname, GLint *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glGetClipPlanex, GLenum, pname, GLfixed *, eqn)
_EVASGL_FUNCTION_BEGIN_VOID( glGenBuffers, GLsizei, n, GLuint *, buffers )
_EVASGL_FUNCTION_BEGIN_VOID( glGenTextures, GLsizei, n, GLuint *, textures )
_EVASGL_FUNCTION_BEGIN_VOID( glGetFixedv, GLenum, pname, GLfixed *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glGetLightxv, GLenum, light, GLenum, pname, GLfixed *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glGetMaterialxv, GLenum, face, GLenum, pname, GLfixed *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glGetPointerv, GLenum, pname, GLvoid **, params)
_EVASGL_FUNCTION_BEGIN_VOID( glGetTexEnviv, GLenum, env, GLenum, pname, GLint *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glGetTexEnvxv, GLenum, env, GLenum, pname, GLfixed *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glGetTexParameteriv, GLenum, target, GLenum, pname, GLint *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glGetTexParameterxv, GLenum, target, GLenum, pname, GLfixed *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glHint, GLenum, target, GLenum, mode )
_EVASGL_FUNCTION_BEGIN_VOID( glLightModelx, GLenum, pname, GLfixed, param )
_EVASGL_FUNCTION_BEGIN_VOID( glLightModelxv, GLenum, pname, const GLfixed *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glLightx, GLenum, light, GLenum, pname, GLfixed, param )
_EVASGL_FUNCTION_BEGIN_VOID( glLightxv, GLenum, light, GLenum, pname, const GLfixed *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glLineWidthx, GLfixed, width )
_EVASGL_FUNCTION_BEGIN_VOID( glLoadIdentity )
_EVASGL_FUNCTION_BEGIN_VOID( glLoadMatrixx, const GLfixed *, m )
_EVASGL_FUNCTION_BEGIN_VOID( glLogicOp, GLenum, opcode )
_EVASGL_FUNCTION_BEGIN_VOID( glMaterialx, GLenum, face, GLenum, pname, GLfixed, param )
_EVASGL_FUNCTION_BEGIN_VOID( glMaterialxv, GLenum, face, GLenum, pname, const GLfixed *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glMatrixMode, GLenum, mode )
_EVASGL_FUNCTION_BEGIN_VOID( glMultMatrixx, const GLfixed *, m )
_EVASGL_FUNCTION_BEGIN_VOID( glMultiTexCoord4x, GLenum, target, GLfixed, s, GLfixed, t, GLfixed, r, GLfixed, q )
_EVASGL_FUNCTION_BEGIN_VOID( glNormal3x, GLfixed, nx, GLfixed, ny, GLfixed, nz )
_EVASGL_FUNCTION_BEGIN_VOID( glNormalPointer, GLenum, type, GLsizei, stride, const GLvoid *, pointer )
_EVASGL_FUNCTION_BEGIN_VOID( glOrthox, GLfixed, left, GLfixed, right, GLfixed, bottom, GLfixed, top, GLfixed, zNear, GLfixed, zFar )
_EVASGL_FUNCTION_BEGIN_VOID( glPixelStorei, GLenum, pname, GLint, param )
_EVASGL_FUNCTION_BEGIN_VOID( glPointParameterx, GLenum, pname, GLfixed, param )
_EVASGL_FUNCTION_BEGIN_VOID( glPointParameterxv, GLenum, pname, const GLfixed *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glPointSizex, GLfixed, size )
_EVASGL_FUNCTION_BEGIN_VOID( glPolygonOffsetx, GLfixed, factor, GLfixed, units )
_EVASGL_FUNCTION_BEGIN_VOID( glPopMatrix )
_EVASGL_FUNCTION_BEGIN_VOID( glPushMatrix )
_EVASGL_FUNCTION_BEGIN_VOID( glRotatex, GLfixed, angle, GLfixed, x, GLfixed, y, GLfixed, z )
_EVASGL_FUNCTION_BEGIN_VOID( glSampleCoverage, GLclampf, value, GLboolean, invert )
_EVASGL_FUNCTION_BEGIN_VOID( glSampleCoveragex, GLclampx, value, GLboolean, invert )
_EVASGL_FUNCTION_BEGIN_VOID( glScalex, GLfixed, x, GLfixed, y, GLfixed, z )
_EVASGL_FUNCTION_BEGIN_VOID( glShadeModel, GLenum, mode )
_EVASGL_FUNCTION_BEGIN_VOID( glStencilFunc, GLenum, func, GLint, ref, GLuint, mask )
_EVASGL_FUNCTION_BEGIN_VOID( glStencilMask, GLuint, mask )
_EVASGL_FUNCTION_BEGIN_VOID( glStencilOp, GLenum, fail, GLenum, zfail, GLenum, zpass )
_EVASGL_FUNCTION_BEGIN_VOID( glTexCoordPointer, GLint, size, GLenum, type, GLsizei, stride, const GLvoid *, pointer )
_EVASGL_FUNCTION_BEGIN_VOID( glTexEnvi, GLenum, target, GLenum, pname, GLint, param )
_EVASGL_FUNCTION_BEGIN_VOID( glTexEnvx, GLenum, target, GLenum, pname, GLfixed, param )
_EVASGL_FUNCTION_BEGIN_VOID( glTexEnviv, GLenum, target, GLenum, pname, const GLint *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glTexEnvxv, GLenum, target, GLenum, pname, const GLfixed *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glTexImage2D, GLenum, target, GLint, level, GLint, internalformat, GLsizei, width, GLsizei, height, GLint, border, GLenum, format, GLenum, type, const GLvoid *, pixels )
_EVASGL_FUNCTION_BEGIN_VOID( glTexParameteri, GLenum, target, GLenum, pname, GLint, param )
_EVASGL_FUNCTION_BEGIN_VOID( glTexParameterx, GLenum, target, GLenum, pname, GLfixed, param )
_EVASGL_FUNCTION_BEGIN_VOID( glTexParameteriv, GLenum, target, GLenum, pname, const GLint *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glTexParameterxv, GLenum, target, GLenum, pname, const GLfixed *, params )
_EVASGL_FUNCTION_BEGIN_VOID( glTexSubImage2D, GLenum, target, GLint, level, GLint, xoffset, GLint, yoffset, GLsizei, width, GLsizei, height, GLenum, format, GLenum, type, const GLvoid *, pixels )
_EVASGL_FUNCTION_BEGIN_VOID( glTranslatex, GLfixed, x, GLfixed, y, GLfixed, z )
_EVASGL_FUNCTION_BEGIN_VOID( glVertexPointer, GLint, size, GLenum, type, GLsizei, stride, const GLvoid *, pointer )
_EVASGL_FUNCTION_PRIVATE_BEGIN_VOID( glClearColor, GLclampf, red, GLclampf, green, GLclampf, blue, GLclampf, alpha )
_EVASGL_FUNCTION_PRIVATE_BEGIN_VOID( glClear, GLbitfield, mask )
_EVASGL_FUNCTION_PRIVATE_BEGIN_VOID( glDisable, GLenum, cap )
_EVASGL_FUNCTION_PRIVATE_BEGIN_VOID( glEnable, GLenum, cap )
_EVASGL_FUNCTION_PRIVATE_BEGIN( GLenum, glGetError, void )
_EVASGL_FUNCTION_PRIVATE_BEGIN_VOID( glGetIntegerv, GLenum, pname, GLint *, params )
_EVASGL_FUNCTION_PRIVATE_BEGIN( const GLubyte *, glGetString, GLenum, name )
_EVASGL_FUNCTION_PRIVATE_BEGIN_VOID( glReadPixels, GLint, x, GLint, y, GLsizei, width, GLsizei, height, GLenum, format, GLenum, type, GLvoid *, pixels )
_EVASGL_FUNCTION_PRIVATE_BEGIN_VOID( glScissor, GLint, x, GLint, y, GLsizei, width, GLsizei, height )
_EVASGL_FUNCTION_PRIVATE_BEGIN_VOID( glViewport, GLint, x, GLint, y, GLsizei, width, GLsizei, height )
_EVASGL_FUNCTION_BEGIN( GLboolean, glIsBuffer, GLuint, buffer )
_EVASGL_FUNCTION_BEGIN( GLboolean, glIsEnabled, GLenum, cap )
_EVASGL_FUNCTION_BEGIN( GLboolean, glIsTexture, GLuint, texture )
