/*
 * This is an automatically generated file using a python script.
 * ($EFL_HOME/src/utils/evas/generate_gl_thread_api.py)
 * Recommend that you modify data files ($EFL_HOME/src/utils/evas/gl_api_def.txt)
 * and make use of scripts if you need to fix them.
 */
GLenum (*evas_glGetError_evgl_th)(void) = NULL;
void (*evas_glVertexAttribPointer_evgl_th)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer) = NULL;
void (*evas_glEnableVertexAttribArray_evgl_th)(GLuint index) = NULL;
void (*evas_glDisableVertexAttribArray_evgl_th)(GLuint index) = NULL;
void (*evas_glDrawArrays_evgl_th)(GLenum mode, GLint first, GLsizei count) = NULL;
void (*evas_glDrawElements_evgl_th)(GLenum mode, GLsizei count, GLenum type, const void *indices) = NULL;
void (*evas_glGenBuffers_evgl_th)(GLsizei n, GLuint *buffers) = NULL;
void (*evas_glDeleteBuffers_evgl_th)(GLsizei n, const GLuint *buffers) = NULL;
void (*evas_glBindBuffer_evgl_th)(GLenum target, GLuint buffer) = NULL;
void (*evas_glBufferData_evgl_th)(GLenum target, GLsizeiptr size, const void *data, GLenum usage) = NULL;
GLuint (*evas_glCreateShader_evgl_th)(GLenum type) = NULL;
void (*evas_glShaderSource_evgl_th)(GLuint shader, GLsizei count, const GLchar **string, const GLint *length) = NULL;
void (*evas_glCompileShader_evgl_th)(GLuint shader) = NULL;
void (*evas_glDeleteShader_evgl_th)(GLuint shader) = NULL;
GLuint (*evas_glCreateProgram_evgl_th)(void) = NULL;
void (*evas_glAttachShader_evgl_th)(GLuint program, GLuint shader) = NULL;
void (*evas_glDetachShader_evgl_th)(GLuint program, GLuint shader) = NULL;
void (*evas_glLinkProgram_evgl_th)(GLuint program) = NULL;
void (*evas_glUseProgram_evgl_th)(GLuint program) = NULL;
void (*evas_glDeleteProgram_evgl_th)(GLuint program) = NULL;
void (*glGetProgramBinary_orig_evgl_set)(void *func) = NULL;
void *(*glGetProgramBinary_orig_evgl_get)(void) = NULL;
void (*evas_glGetProgramBinary_evgl_th)(GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary) = NULL;
void (*glProgramBinary_orig_evgl_set)(void *func) = NULL;
void *(*glProgramBinary_orig_evgl_get)(void) = NULL;
void (*evas_glProgramBinary_evgl_th)(GLuint program, GLenum binaryFormat, const void *binary, GLint length) = NULL;
void (*evas_glGetActiveAttrib_evgl_th)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name) = NULL;
GLint (*evas_glGetAttribLocation_evgl_th)(GLuint program, const GLchar *name) = NULL;
void (*evas_glBindAttribLocation_evgl_th)(GLuint program, GLuint index, const GLchar *name) = NULL;
GLint (*evas_glGetUniformLocation_evgl_th)(GLuint program, const GLchar *name) = NULL;
void (*evas_glUniform1f_evgl_th)(GLint location, GLfloat v0) = NULL;
void (*evas_glUniform1i_evgl_th)(GLint location, GLint v0) = NULL;
void (*evas_glUniform2f_evgl_th)(GLint location, GLfloat v0, GLfloat v1) = NULL;
void (*evas_glUniform2i_evgl_th)(GLint location, GLint v0, GLint v1) = NULL;
void (*evas_glUniform3f_evgl_th)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2) = NULL;
void (*evas_glUniform3i_evgl_th)(GLint location, GLint v0, GLint v1, GLint v2) = NULL;
void (*evas_glUniform4f_evgl_th)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) = NULL;
void (*evas_glUniform4i_evgl_th)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3) = NULL;
void (*evas_glUniform1fv_evgl_th)(GLint location, GLsizei count, const GLfloat *value) = NULL;
void (*evas_glUniform1iv_evgl_th)(GLint location, GLsizei count, const GLint *value) = NULL;
void (*evas_glUniform2fv_evgl_th)(GLint location, GLsizei count, const GLfloat *value) = NULL;
void (*evas_glUniform2iv_evgl_th)(GLint location, GLsizei count, const GLint *value) = NULL;
void (*evas_glUniform3fv_evgl_th)(GLint location, GLsizei count, const GLfloat *value) = NULL;
void (*evas_glUniform3iv_evgl_th)(GLint location, GLsizei count, const GLint *value) = NULL;
void (*evas_glUniform4fv_evgl_th)(GLint location, GLsizei count, const GLfloat *value) = NULL;
void (*evas_glUniform4iv_evgl_th)(GLint location, GLsizei count, const GLint *value) = NULL;
void (*evas_glUniformMatrix2fv_evgl_th)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) = NULL;
void (*evas_glUniformMatrix3fv_evgl_th)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) = NULL;
void (*evas_glUniformMatrix4fv_evgl_th)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) = NULL;
void (*evas_glViewport_evgl_th)(GLint x, GLint y, GLsizei width, GLsizei height) = NULL;
void (*evas_glEnable_evgl_th)(GLenum cap) = NULL;
void (*evas_glDisable_evgl_th)(GLenum cap) = NULL;
void (*evas_glLineWidth_evgl_th)(GLfloat width) = NULL;
void (*evas_glPolygonOffset_evgl_th)(GLfloat factor, GLfloat units) = NULL;
void (*evas_glPixelStorei_evgl_th)(GLenum pname, GLint param) = NULL;
void (*evas_glActiveTexture_evgl_th)(GLenum texture) = NULL;
void (*evas_glGenTextures_evgl_th)(GLsizei n, GLuint *textures) = NULL;
void (*evas_glBindTexture_evgl_th)(GLenum target, GLuint texture) = NULL;
void (*evas_glDeleteTextures_evgl_th)(GLsizei n, const GLuint *textures) = NULL;
void (*evas_glTexImage2D_evgl_th)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels) = NULL;
void (*evas_glTexSubImage2D_evgl_th)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels) = NULL;
void (*evas_glCompressedTexImage2D_evgl_th)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data) = NULL;
void (*evas_glCompressedTexSubImage2D_evgl_th)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data) = NULL;
void (*evas_glTexParameterf_evgl_th)(GLenum target, GLenum pname, GLfloat param) = NULL;
void (*evas_glTexParameterfv_evgl_th)(GLenum target, GLenum pname, const GLfloat *params) = NULL;
void (*evas_glTexParameteri_evgl_th)(GLenum target, GLenum pname, GLint param) = NULL;
void (*evas_glTexParameteriv_evgl_th)(GLenum target, GLenum pname, const GLint *params) = NULL;
void (*evas_glScissor_evgl_th)(GLint x, GLint y, GLsizei width, GLsizei height) = NULL;
void (*evas_glBlendFunc_evgl_th)(GLenum sfactor, GLenum dfactor) = NULL;
void (*evas_glBlendColor_evgl_th)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) = NULL;
void (*evas_glDepthMask_evgl_th)(GLboolean flag) = NULL;
void (*evas_glClear_evgl_th)(GLbitfield mask) = NULL;
void (*evas_glClearColor_evgl_th)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) = NULL;
void (*evas_glReadPixels_evgl_th)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels) = NULL;
void (*evas_glGenFramebuffers_evgl_th)(GLsizei n, GLuint *framebuffers) = NULL;
void (*evas_glBindFramebuffer_evgl_th)(GLenum target, GLuint framebuffer) = NULL;
void (*evas_glDeleteFramebuffers_evgl_th)(GLsizei n, const GLuint *framebuffers) = NULL;
void (*evas_glGenRenderbuffers_evgl_th)(GLsizei n, GLuint *renderbuffers) = NULL;
void (*evas_glBindRenderbuffer_evgl_th)(GLenum target, GLuint renderbuffer) = NULL;
void (*evas_glDeleteRenderbuffers_evgl_th)(GLsizei n, const GLuint *renderbuffers) = NULL;
void (*evas_glRenderbufferStorage_evgl_th)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height) = NULL;
void (*evas_glFramebufferRenderbuffer_evgl_th)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) = NULL;
void (*evas_glFramebufferTexture2D_evgl_th)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) = NULL;
GLenum (*evas_glCheckFramebufferStatus_evgl_th)(GLenum target) = NULL;
void (*evas_glFlush_evgl_th)(void) = NULL;
void (*evas_glFinish_evgl_th)(void) = NULL;
void (*evas_glHint_evgl_th)(GLenum target, GLenum mode) = NULL;
const GLubyte * (*evas_glGetString_evgl_th)(GLenum name) = NULL;
void (*evas_glGetBooleanv_evgl_th)(GLenum pname, GLboolean *data) = NULL;
void (*evas_glGetFloatv_evgl_th)(GLenum pname, GLfloat *data) = NULL;
void (*evas_glGetIntegerv_evgl_th)(GLenum pname, GLint *data) = NULL;
GLboolean (*evas_glIsBuffer_evgl_th)(GLint buffer) = NULL;
void (*evas_glGetBufferParameteriv_evgl_th)(GLenum target, GLenum pname, GLint *params) = NULL;
GLboolean (*evas_glIsShader_evgl_th)(GLuint shader) = NULL;
void (*evas_glGetShaderiv_evgl_th)(GLuint shader, GLenum pname, GLint *params) = NULL;
void (*evas_glGetAttachedShaders_evgl_th)(GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders) = NULL;
void (*evas_glGetShaderInfoLog_evgl_th)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog) = NULL;
void (*evas_glGetShaderSource_evgl_th)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source) = NULL;
void (*evas_glGetShaderPrecisionFormat_evgl_th)(GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision) = NULL;
void (*evas_glGetVertexAttribfv_evgl_th)(GLuint index, GLenum pname, GLfloat *params) = NULL;
void (*evas_glGetVertexAttribiv_evgl_th)(GLuint index, GLenum pname, GLint *params) = NULL;
GLboolean (*evas_glIsProgram_evgl_th)(GLuint program) = NULL;
void (*evas_glGetProgramInfoLog_evgl_th)(GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog) = NULL;
void (*evas_glGetProgramiv_evgl_th)(GLuint program, GLenum pname, GLint *params) = NULL;
GLboolean (*evas_glIsFramebuffer_evgl_th)(GLint framebuffer) = NULL;
GLboolean (*evas_glIsRenderbuffer_evgl_th)(GLint renderbuffer) = NULL;
void (*evas_glGetRenderbufferParameteriv_evgl_th)(GLenum target, GLenum pname, GLint *params) = NULL;
GLboolean (*evas_glIsTexture_evgl_th)(GLint texture) = NULL;
void (*evas_glClearDepthf_evgl_th)(GLclampf depth) = NULL;
void (*evas_glDepthRangef_evgl_th)(GLclampf zNear, GLclampf zFar) = NULL;
void (*evas_glClearDepth_evgl_th)(GLclampf depth) = NULL;
void (*evas_glDepthRange_evgl_th)(GLclampf zNear, GLclampf zFar) = NULL;
void (*evas_glGetFramebufferAttachmentParameteriv_evgl_th)(GLenum target, GLenum attachment, GLenum pname, GLint* params) = NULL;


void
_gl_thread_link_evgl_generated_init()
{
#define LINK2GENERIC(sym) \
   sym = dlsym(RTLD_DEFAULT, #sym); \
   if (!sym) ERR("Could not find function '%s'", #sym);

   LINK2GENERIC(evas_glGetError_evgl_th);
   LINK2GENERIC(evas_glVertexAttribPointer_evgl_th);
   LINK2GENERIC(evas_glEnableVertexAttribArray_evgl_th);
   LINK2GENERIC(evas_glDisableVertexAttribArray_evgl_th);
   LINK2GENERIC(evas_glDrawArrays_evgl_th);
   LINK2GENERIC(evas_glDrawElements_evgl_th);
   LINK2GENERIC(evas_glGenBuffers_evgl_th);
   LINK2GENERIC(evas_glDeleteBuffers_evgl_th);
   LINK2GENERIC(evas_glBindBuffer_evgl_th);
   LINK2GENERIC(evas_glBufferData_evgl_th);
   LINK2GENERIC(evas_glCreateShader_evgl_th);
   LINK2GENERIC(evas_glShaderSource_evgl_th);
   LINK2GENERIC(evas_glCompileShader_evgl_th);
   LINK2GENERIC(evas_glDeleteShader_evgl_th);
   LINK2GENERIC(evas_glCreateProgram_evgl_th);
   LINK2GENERIC(evas_glAttachShader_evgl_th);
   LINK2GENERIC(evas_glDetachShader_evgl_th);
   LINK2GENERIC(evas_glLinkProgram_evgl_th);
   LINK2GENERIC(evas_glUseProgram_evgl_th);
   LINK2GENERIC(evas_glDeleteProgram_evgl_th);
   LINK2GENERIC(glGetProgramBinary_orig_evgl_set);
   LINK2GENERIC(glGetProgramBinary_orig_evgl_get);
   LINK2GENERIC(evas_glGetProgramBinary_evgl_th);
   LINK2GENERIC(glProgramBinary_orig_evgl_set);
   LINK2GENERIC(glProgramBinary_orig_evgl_get);
   LINK2GENERIC(evas_glProgramBinary_evgl_th);
   LINK2GENERIC(evas_glGetActiveAttrib_evgl_th);
   LINK2GENERIC(evas_glGetAttribLocation_evgl_th);
   LINK2GENERIC(evas_glBindAttribLocation_evgl_th);
   LINK2GENERIC(evas_glGetUniformLocation_evgl_th);
   LINK2GENERIC(evas_glUniform1f_evgl_th);
   LINK2GENERIC(evas_glUniform1i_evgl_th);
   LINK2GENERIC(evas_glUniform2f_evgl_th);
   LINK2GENERIC(evas_glUniform2i_evgl_th);
   LINK2GENERIC(evas_glUniform3f_evgl_th);
   LINK2GENERIC(evas_glUniform3i_evgl_th);
   LINK2GENERIC(evas_glUniform4f_evgl_th);
   LINK2GENERIC(evas_glUniform4i_evgl_th);
   LINK2GENERIC(evas_glUniform1fv_evgl_th);
   LINK2GENERIC(evas_glUniform1iv_evgl_th);
   LINK2GENERIC(evas_glUniform2fv_evgl_th);
   LINK2GENERIC(evas_glUniform2iv_evgl_th);
   LINK2GENERIC(evas_glUniform3fv_evgl_th);
   LINK2GENERIC(evas_glUniform3iv_evgl_th);
   LINK2GENERIC(evas_glUniform4fv_evgl_th);
   LINK2GENERIC(evas_glUniform4iv_evgl_th);
   LINK2GENERIC(evas_glUniformMatrix2fv_evgl_th);
   LINK2GENERIC(evas_glUniformMatrix3fv_evgl_th);
   LINK2GENERIC(evas_glUniformMatrix4fv_evgl_th);
   LINK2GENERIC(evas_glViewport_evgl_th);
   LINK2GENERIC(evas_glEnable_evgl_th);
   LINK2GENERIC(evas_glDisable_evgl_th);
   LINK2GENERIC(evas_glLineWidth_evgl_th);
   LINK2GENERIC(evas_glPolygonOffset_evgl_th);
   LINK2GENERIC(evas_glPixelStorei_evgl_th);
   LINK2GENERIC(evas_glActiveTexture_evgl_th);
   LINK2GENERIC(evas_glGenTextures_evgl_th);
   LINK2GENERIC(evas_glBindTexture_evgl_th);
   LINK2GENERIC(evas_glDeleteTextures_evgl_th);
   LINK2GENERIC(evas_glTexImage2D_evgl_th);
   LINK2GENERIC(evas_glTexSubImage2D_evgl_th);
   LINK2GENERIC(evas_glCompressedTexImage2D_evgl_th);
   LINK2GENERIC(evas_glCompressedTexSubImage2D_evgl_th);
   LINK2GENERIC(evas_glTexParameterf_evgl_th);
   LINK2GENERIC(evas_glTexParameterfv_evgl_th);
   LINK2GENERIC(evas_glTexParameteri_evgl_th);
   LINK2GENERIC(evas_glTexParameteriv_evgl_th);
   LINK2GENERIC(evas_glScissor_evgl_th);
   LINK2GENERIC(evas_glBlendFunc_evgl_th);
   LINK2GENERIC(evas_glBlendColor_evgl_th);
   LINK2GENERIC(evas_glDepthMask_evgl_th);
   LINK2GENERIC(evas_glClear_evgl_th);
   LINK2GENERIC(evas_glClearColor_evgl_th);
   LINK2GENERIC(evas_glReadPixels_evgl_th);
   LINK2GENERIC(evas_glGenFramebuffers_evgl_th);
   LINK2GENERIC(evas_glBindFramebuffer_evgl_th);
   LINK2GENERIC(evas_glDeleteFramebuffers_evgl_th);
   LINK2GENERIC(evas_glGenRenderbuffers_evgl_th);
   LINK2GENERIC(evas_glBindRenderbuffer_evgl_th);
   LINK2GENERIC(evas_glDeleteRenderbuffers_evgl_th);
   LINK2GENERIC(evas_glRenderbufferStorage_evgl_th);
   LINK2GENERIC(evas_glFramebufferRenderbuffer_evgl_th);
   LINK2GENERIC(evas_glFramebufferTexture2D_evgl_th);
   LINK2GENERIC(evas_glCheckFramebufferStatus_evgl_th);
   LINK2GENERIC(evas_glFlush_evgl_th);
   LINK2GENERIC(evas_glFinish_evgl_th);
   LINK2GENERIC(evas_glHint_evgl_th);
   LINK2GENERIC(evas_glGetString_evgl_th);
   LINK2GENERIC(evas_glGetBooleanv_evgl_th);
   LINK2GENERIC(evas_glGetFloatv_evgl_th);
   LINK2GENERIC(evas_glGetIntegerv_evgl_th);
   LINK2GENERIC(evas_glIsBuffer_evgl_th);
   LINK2GENERIC(evas_glGetBufferParameteriv_evgl_th);
   LINK2GENERIC(evas_glIsShader_evgl_th);
   LINK2GENERIC(evas_glGetShaderiv_evgl_th);
   LINK2GENERIC(evas_glGetAttachedShaders_evgl_th);
   LINK2GENERIC(evas_glGetShaderInfoLog_evgl_th);
   LINK2GENERIC(evas_glGetShaderSource_evgl_th);
   LINK2GENERIC(evas_glGetShaderPrecisionFormat_evgl_th);
   LINK2GENERIC(evas_glGetVertexAttribfv_evgl_th);
   LINK2GENERIC(evas_glGetVertexAttribiv_evgl_th);
   LINK2GENERIC(evas_glIsProgram_evgl_th);
   LINK2GENERIC(evas_glGetProgramInfoLog_evgl_th);
   LINK2GENERIC(evas_glGetProgramiv_evgl_th);
   LINK2GENERIC(evas_glIsFramebuffer_evgl_th);
   LINK2GENERIC(evas_glIsRenderbuffer_evgl_th);
   LINK2GENERIC(evas_glGetRenderbufferParameteriv_evgl_th);
   LINK2GENERIC(evas_glIsTexture_evgl_th);
   LINK2GENERIC(evas_glClearDepthf_evgl_th);
   LINK2GENERIC(evas_glDepthRangef_evgl_th);
   LINK2GENERIC(evas_glClearDepth_evgl_th);
   LINK2GENERIC(evas_glDepthRange_evgl_th);
   LINK2GENERIC(evas_glGetFramebufferAttachmentParameteriv_evgl_th);
}
