/*
 * ------------------------------------------------------------------------------
 * This is an automatically generated file using a python script.
 * ($EFL_HOME/src/utils/evas/generate_gl_thread_api.py)
 * Recommend that you modify data files ($EFL_HOME/src/utils/evas/gl_api_def.txt)
 * and make use of scripts if you need to fix them.
 * ------------------------------------------------------------------------------
 */

extern void (*GL_TH_FN(glActiveTexture))(GL_TH_DP, GLenum texture);
extern void (*GL_TH_FN(glAttachShader))(GL_TH_DP, GLuint program, GLuint shader);
extern void (*GL_TH_FN(glBindAttribLocation))(GL_TH_DP, GLuint program, GLuint index, const char* name);
extern void (*GL_TH_FN(glBindBuffer))(GL_TH_DP, GLenum target, GLuint buffer);
extern void (*GL_TH_FN(glBindFramebuffer))(GL_TH_DP, GLenum target, GLuint framebuffer);
extern void (*GL_TH_FN(glBindRenderbuffer))(GL_TH_DP, GLenum target, GLuint renderbuffer);
extern void (*GL_TH_FN(glBindTexture))(GL_TH_DP, GLenum target, GLuint texture);
extern void (*GL_TH_FN(glBlendColor))(GL_TH_DP, GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
extern void (*GL_TH_FN(glBlendEquation))(GL_TH_DP, GLenum mode);
extern void (*GL_TH_FN(glBlendEquationSeparate))(GL_TH_DP, GLenum modeRGB, GLenum modeAlpha);
extern void (*GL_TH_FN(glBlendFunc))(GL_TH_DP, GLenum sfactor, GLenum dfactor);
extern void (*GL_TH_FN(glBlendFuncSeparate))(GL_TH_DP, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
extern void (*GL_TH_FN(glBufferData))(GL_TH_DP, GLenum target, GLsizeiptr size, const void* data, GLenum usage);
extern void (*GL_TH_FN(glBufferSubData))(GL_TH_DP, GLenum target, GLintptr offset, GLsizeiptr size, const void* data);
extern GLenum (*GL_TH_FN(glCheckFramebufferStatus))(GL_TH_DP, GLenum target);
extern void (*GL_TH_FN(glClear))(GL_TH_DP, GLbitfield mask);
extern void (*GL_TH_FN(glClearColor))(GL_TH_DP, GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
extern void (*GL_TH_FN(glClearDepthf))(GL_TH_DP, GLclampf depth);
extern void (*GL_TH_FN(glClearStencil))(GL_TH_DP, GLint s);
extern void (*GL_TH_FN(glColorMask))(GL_TH_DP, GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
extern void (*GL_TH_FN(glCompileShader))(GL_TH_DP, GLuint shader);
extern void (*GL_TH_FN(glCompressedTexImage2D))(GL_TH_DP, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void* data);
extern void (*GL_TH_FN(glCompressedTexSubImage2D))(GL_TH_DP, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void* data);
extern void (*GL_TH_FN(glCopyTexImage2D))(GL_TH_DP, GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
extern void (*GL_TH_FN(glCopyTexSubImage2D))(GL_TH_DP, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern GLuint (*GL_TH_FN(glCreateProgram))(GL_TH_DP);
extern GLuint (*GL_TH_FN(glCreateShader))(GL_TH_DP, GLenum type);
extern void (*GL_TH_FN(glCullFace))(GL_TH_DP, GLenum mode);
extern void (*GL_TH_FN(glDeleteBuffers))(GL_TH_DP, GLsizei n, const GLuint* buffers);
extern void (*GL_TH_FN(glDeleteFramebuffers))(GL_TH_DP, GLsizei n, const GLuint* framebuffers);
extern void (*GL_TH_FN(glDeleteProgram))(GL_TH_DP, GLuint program);
extern void (*GL_TH_FN(glDeleteRenderbuffers))(GL_TH_DP, GLsizei n, const GLuint* renderbuffers);
extern void (*GL_TH_FN(glDeleteShader))(GL_TH_DP, GLuint shader);
extern void (*GL_TH_FN(glDeleteTextures))(GL_TH_DP, GLsizei n, const GLuint* textures);
extern void (*GL_TH_FN(glDepthFunc))(GL_TH_DP, GLenum func);
extern void (*GL_TH_FN(glDepthMask))(GL_TH_DP, GLboolean flag);
extern void (*GL_TH_FN(glDepthRangef))(GL_TH_DP, GLclampf zNear, GLclampf zFar);
extern void (*GL_TH_FN(glDetachShader))(GL_TH_DP, GLuint program, GLuint shader);
extern void (*GL_TH_FN(glDisable))(GL_TH_DP, GLenum cap);
extern void (*GL_TH_FN(glDisableVertexAttribArray))(GL_TH_DP, GLuint index);
extern void (*GL_TH_FN(glDrawArrays))(GL_TH_DP, GLenum mode, GLint first, GLsizei count);
extern void (*GL_TH_FN(glDrawElements))(GL_TH_DP, GLenum mode, GLsizei count, GLenum type, const void* indices);
extern void (*GL_TH_FN(glEnable))(GL_TH_DP, GLenum cap);
extern void (*GL_TH_FN(glEnableVertexAttribArray))(GL_TH_DP, GLuint index);
extern void (*GL_TH_FN(glFinish))(GL_TH_DP);
extern void (*GL_TH_FN(glFlush))(GL_TH_DP);
extern void (*GL_TH_FN(glFramebufferRenderbuffer))(GL_TH_DP, GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
extern void (*GL_TH_FN(glFramebufferTexture2D))(GL_TH_DP, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
extern void (*GL_TH_FN(glFrontFace))(GL_TH_DP, GLenum mode);
extern void (*GL_TH_FN(glGenBuffers))(GL_TH_DP, GLsizei n, GLuint* buffers);
extern void (*GL_TH_FN(glGenerateMipmap))(GL_TH_DP, GLenum target);
extern void (*GL_TH_FN(glGenFramebuffers))(GL_TH_DP, GLsizei n, GLuint* framebuffers);
extern void (*GL_TH_FN(glGenRenderbuffers))(GL_TH_DP, GLsizei n, GLuint* renderbuffers);
extern void (*GL_TH_FN(glGenTextures))(GL_TH_DP, GLsizei n, GLuint* textures);
extern void (*GL_TH_FN(glGetActiveAttrib))(GL_TH_DP, GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, char* name);
extern void (*GL_TH_FN(glGetActiveUniform))(GL_TH_DP, GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, char* name);
extern void (*GL_TH_FN(glGetAttachedShaders))(GL_TH_DP, GLuint program, GLsizei maxcount, GLsizei* count, GLuint* shaders);
extern int (*GL_TH_FN(glGetAttribLocation))(GL_TH_DP, GLuint program, const char* name);
extern void (*GL_TH_FN(glGetBooleanv))(GL_TH_DP, GLenum pname, GLboolean* params);
extern void (*GL_TH_FN(glGetBufferParameteriv))(GL_TH_DP, GLenum target, GLenum pname, GLint* params);
extern GLenum (*GL_TH_FN(glGetError))(GL_TH_DP);
extern void (*GL_TH_FN(glGetFloatv))(GL_TH_DP, GLenum pname, GLfloat* params);
extern void (*GL_TH_FN(glGetFramebufferAttachmentParameteriv))(GL_TH_DP, GLenum target, GLenum attachment, GLenum pname, GLint* params);
extern void (*GL_TH_FN(glGetIntegerv))(GL_TH_DP, GLenum pname, GLint* params);
extern void (*GL_TH_FN(glGetProgramiv))(GL_TH_DP, GLuint program, GLenum pname, GLint* params);
extern void (*GL_TH_FN(glGetProgramInfoLog))(GL_TH_DP, GLuint program, GLsizei bufsize, GLsizei* length, char* infolog);
extern void (*GL_TH_FN(glGetRenderbufferParameteriv))(GL_TH_DP, GLenum target, GLenum pname, GLint* params);
extern void (*GL_TH_FN(glGetShaderiv))(GL_TH_DP, GLuint shader, GLenum pname, GLint* params);
extern void (*GL_TH_FN(glGetShaderInfoLog))(GL_TH_DP, GLuint shader, GLsizei bufsize, GLsizei* length, char* infolog);
extern void (*GL_TH_FN(glGetShaderPrecisionFormat))(GL_TH_DP, GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision);
extern void (*GL_TH_FN(glGetShaderSource))(GL_TH_DP, GLuint shader, GLsizei bufsize, GLsizei* length, char* source);
extern const GLubyte* (*GL_TH_FN(glGetString))(GL_TH_DP, GLenum name);
extern void (*GL_TH_FN(glGetTexParameterfv))(GL_TH_DP, GLenum target, GLenum pname, GLfloat* params);
extern void (*GL_TH_FN(glGetTexParameteriv))(GL_TH_DP, GLenum target, GLenum pname, GLint* params);
extern void (*GL_TH_FN(glGetUniformfv))(GL_TH_DP, GLuint program, GLint location, GLfloat* params);
extern void (*GL_TH_FN(glGetUniformiv))(GL_TH_DP, GLuint program, GLint location, GLint* params);
extern int (*GL_TH_FN(glGetUniformLocation))(GL_TH_DP, GLuint program, const char* name);
extern void (*GL_TH_FN(glGetVertexAttribfv))(GL_TH_DP, GLuint index, GLenum pname, GLfloat* params);
extern void (*GL_TH_FN(glGetVertexAttribiv))(GL_TH_DP, GLuint index, GLenum pname, GLint* params);
extern void (*GL_TH_FN(glGetVertexAttribPointerv))(GL_TH_DP, GLuint index, GLenum pname, void** pointer);
extern void (*GL_TH_FN(glHint))(GL_TH_DP, GLenum target, GLenum mode);
extern GLboolean (*GL_TH_FN(glIsBuffer))(GL_TH_DP, GLuint buffer);
extern GLboolean (*GL_TH_FN(glIsEnabled))(GL_TH_DP, GLenum cap);
extern GLboolean (*GL_TH_FN(glIsFramebuffer))(GL_TH_DP, GLuint framebuffer);
extern GLboolean (*GL_TH_FN(glIsProgram))(GL_TH_DP, GLuint program);
extern GLboolean (*GL_TH_FN(glIsRenderbuffer))(GL_TH_DP, GLuint renderbuffer);
extern GLboolean (*GL_TH_FN(glIsShader))(GL_TH_DP, GLuint shader);
extern GLboolean (*GL_TH_FN(glIsTexture))(GL_TH_DP, GLuint texture);
extern void (*GL_TH_FN(glLineWidth))(GL_TH_DP, GLfloat width);
extern void (*GL_TH_FN(glLinkProgram))(GL_TH_DP, GLuint program);
extern void (*GL_TH_FN(glPixelStorei))(GL_TH_DP, GLenum pname, GLint param);
extern void (*GL_TH_FN(glPolygonOffset))(GL_TH_DP, GLfloat factor, GLfloat units);
extern void (*GL_TH_FN(glReadPixels))(GL_TH_DP, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void* pixels);
extern void (*GL_TH_FN(glReleaseShaderCompiler))(GL_TH_DP);
extern void (*GL_TH_FN(glRenderbufferStorage))(GL_TH_DP, GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
extern void (*GL_TH_FN(glSampleCoverage))(GL_TH_DP, GLclampf value, GLboolean invert);
extern void (*GL_TH_FN(glScissor))(GL_TH_DP, GLint x, GLint y, GLsizei width, GLsizei height);
extern void (*GL_TH_FN(glShaderBinary))(GL_TH_DP, GLsizei n, const GLuint* shaders, GLenum binaryformat, const void* binary, GLsizei length);
extern void (*GL_TH_FN(glShaderSource))(GL_TH_DP, GLuint shader, GLsizei count, const char* const * string, const GLint* length);
extern void (*GL_TH_FN(glStencilFunc))(GL_TH_DP, GLenum func, GLint ref, GLuint mask);
extern void (*GL_TH_FN(glStencilFuncSeparate))(GL_TH_DP, GLenum face, GLenum func, GLint ref, GLuint mask);
extern void (*GL_TH_FN(glStencilMask))(GL_TH_DP, GLuint mask);
extern void (*GL_TH_FN(glStencilMaskSeparate))(GL_TH_DP, GLenum face, GLuint mask);
extern void (*GL_TH_FN(glStencilOp))(GL_TH_DP, GLenum fail, GLenum zfail, GLenum zpass);
extern void (*GL_TH_FN(glStencilOpSeparate))(GL_TH_DP, GLenum face, GLenum fail, GLenum zfail, GLenum zpass);
extern void (*GL_TH_FN(glTexImage2D))(GL_TH_DP, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void* pixels);
extern void (*GL_TH_FN(glTexParameterf))(GL_TH_DP, GLenum target, GLenum pname, GLfloat param);
extern void (*GL_TH_FN(glTexParameterfv))(GL_TH_DP, GLenum target, GLenum pname, const GLfloat* params);
extern void (*GL_TH_FN(glTexParameteri))(GL_TH_DP, GLenum target, GLenum pname, GLint param);
extern void (*GL_TH_FN(glTexParameteriv))(GL_TH_DP, GLenum target, GLenum pname, const GLint* params);
extern void (*GL_TH_FN(glTexSubImage2D))(GL_TH_DP, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void* pixels);
extern void (*GL_TH_FN(glUniform1f))(GL_TH_DP, GLint location, GLfloat x);
extern void (*GL_TH_FN(glUniform1fv))(GL_TH_DP, GLint location, GLsizei count, const GLfloat* v);
extern void (*GL_TH_FN(glUniform1i))(GL_TH_DP, GLint location, GLint x);
extern void (*GL_TH_FN(glUniform1iv))(GL_TH_DP, GLint location, GLsizei count, const GLint* v);
extern void (*GL_TH_FN(glUniform2f))(GL_TH_DP, GLint location, GLfloat x, GLfloat y);
extern void (*GL_TH_FN(glUniform2fv))(GL_TH_DP, GLint location, GLsizei count, const GLfloat* v);
extern void (*GL_TH_FN(glUniform2i))(GL_TH_DP, GLint location, GLint x, GLint y);
extern void (*GL_TH_FN(glUniform2iv))(GL_TH_DP, GLint location, GLsizei count, const GLint* v);
extern void (*GL_TH_FN(glUniform3f))(GL_TH_DP, GLint location, GLfloat x, GLfloat y, GLfloat z);
extern void (*GL_TH_FN(glUniform3fv))(GL_TH_DP, GLint location, GLsizei count, const GLfloat* v);
extern void (*GL_TH_FN(glUniform3i))(GL_TH_DP, GLint location, GLint x, GLint y, GLint z);
extern void (*GL_TH_FN(glUniform3iv))(GL_TH_DP, GLint location, GLsizei count, const GLint* v);
extern void (*GL_TH_FN(glUniform4f))(GL_TH_DP, GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
extern void (*GL_TH_FN(glUniform4fv))(GL_TH_DP, GLint location, GLsizei count, const GLfloat* v);
extern void (*GL_TH_FN(glUniform4i))(GL_TH_DP, GLint location, GLint x, GLint y, GLint z, GLint w);
extern void (*GL_TH_FN(glUniform4iv))(GL_TH_DP, GLint location, GLsizei count, const GLint* v);
extern void (*GL_TH_FN(glUniformMatrix2fv))(GL_TH_DP, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*GL_TH_FN(glUniformMatrix3fv))(GL_TH_DP, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*GL_TH_FN(glUniformMatrix4fv))(GL_TH_DP, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*GL_TH_FN(glUseProgram))(GL_TH_DP, GLuint program);
extern void (*GL_TH_FN(glValidateProgram))(GL_TH_DP, GLuint program);
extern void (*GL_TH_FN(glVertexAttrib1f))(GL_TH_DP, GLuint indx, GLfloat x);
extern void (*GL_TH_FN(glVertexAttrib1fv))(GL_TH_DP, GLuint indx, const GLfloat* values);
extern void (*GL_TH_FN(glVertexAttrib2f))(GL_TH_DP, GLuint indx, GLfloat x, GLfloat y);
extern void (*GL_TH_FN(glVertexAttrib2fv))(GL_TH_DP, GLuint indx, const GLfloat* values);
extern void (*GL_TH_FN(glVertexAttrib3f))(GL_TH_DP, GLuint indx, GLfloat x, GLfloat y, GLfloat z);
extern void (*GL_TH_FN(glVertexAttrib3fv))(GL_TH_DP, GLuint indx, const GLfloat* values);
extern void (*GL_TH_FN(glVertexAttrib4f))(GL_TH_DP, GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
extern void (*GL_TH_FN(glVertexAttrib4fv))(GL_TH_DP, GLuint indx, const GLfloat* values);
extern void (*GL_TH_FN(glVertexAttribPointer))(GL_TH_DP, GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void* ptr);
extern void (*GL_TH_FN(glViewport))(GL_TH_DP, GLint x, GLint y, GLsizei width, GLsizei height);
extern void (*GL_TH_FN(glEvasGLImageTargetTexture2DOES))(GL_TH_DP, GLenum target, EvasGLImage image);
extern void (*GL_TH_FN(glEvasGLImageTargetRenderbufferStorageOES))(GL_TH_DP, GLenum target, EvasGLImage image);
extern void (*GL_TH_FN(glGetProgramBinaryOES))(GL_TH_DP, GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary);
extern void (*GL_TH_FN(glProgramBinaryOES))(GL_TH_DP, GLuint program, GLenum binaryFormat, const void *binary, GLint length);
extern void * (*GL_TH_FN(glMapBufferOES))(GL_TH_DP, GLenum target, GLenum access);
extern GLboolean (*GL_TH_FN(glUnmapBufferOES))(GL_TH_DP, GLenum target);
extern void (*GL_TH_FN(glGetBufferPointervOES))(GL_TH_DP, GLenum target, GLenum pname, void** params);
extern void (*GL_TH_FN(glTexImage3DOES))(GL_TH_DP, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void* pixels);
extern void (*GL_TH_FN(glTexSubImage3DOES))(GL_TH_DP, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void* pixels);
extern void (*GL_TH_FN(glCopyTexSubImage3DOES))(GL_TH_DP, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern void (*GL_TH_FN(glCompressedTexImage3DOES))(GL_TH_DP, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void* data);
extern void (*GL_TH_FN(glCompressedTexSubImage3DOES))(GL_TH_DP, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void* data);
extern void (*GL_TH_FN(glFramebufferTexture3DOES))(GL_TH_DP, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset);
extern void (*GL_TH_FN(glGetPerfMonitorGroupsAMD))(GL_TH_DP, GLint* numGroups, GLsizei groupsSize, GLuint* groups);
extern void (*GL_TH_FN(glGetPerfMonitorCountersAMD))(GL_TH_DP, GLuint group, GLint* numCounters, GLint* maxActiveCounters, GLsizei counterSize, GLuint* counters);
extern void (*GL_TH_FN(glGetPerfMonitorGroupStringAMD))(GL_TH_DP, GLuint group, GLsizei bufSize, GLsizei* length, char* groupString);
extern void (*GL_TH_FN(glGetPerfMonitorCounterStringAMD))(GL_TH_DP, GLuint group, GLuint counter, GLsizei bufSize, GLsizei* length, char* counterString);
extern void (*GL_TH_FN(glGetPerfMonitorCounterInfoAMD))(GL_TH_DP, GLuint group, GLuint counter, GLenum pname, void* data);
extern void (*GL_TH_FN(glGenPerfMonitorsAMD))(GL_TH_DP, GLsizei n, GLuint* monitors);
extern void (*GL_TH_FN(glDeletePerfMonitorsAMD))(GL_TH_DP, GLsizei n, GLuint* monitors);
extern void (*GL_TH_FN(glSelectPerfMonitorCountersAMD))(GL_TH_DP, GLuint monitor, GLboolean enable, GLuint group, GLint numCounters, GLuint* countersList);
extern void (*GL_TH_FN(glBeginPerfMonitorAMD))(GL_TH_DP, GLuint monitor);
extern void (*GL_TH_FN(glEndPerfMonitorAMD))(GL_TH_DP, GLuint monitor);
extern void (*GL_TH_FN(glGetPerfMonitorCounterDataAMD))(GL_TH_DP, GLuint monitor, GLenum pname, GLsizei dataSize, GLuint* data, GLint* bytesWritten);
extern void (*GL_TH_FN(glDiscardFramebufferEXT))(GL_TH_DP, GLenum target, GLsizei numAttachments, const GLenum* attachments);
extern void (*GL_TH_FN(glMultiDrawArraysEXT))(GL_TH_DP, GLenum mode, GLint* first, GLsizei* count, GLsizei primcount);
extern void (*GL_TH_FN(glMultiDrawElementsEXT))(GL_TH_DP, GLenum mode, const GLsizei* count, GLenum type, const GLvoid** indices, GLsizei primcount);
extern void (*GL_TH_FN(glDeleteFencesNV))(GL_TH_DP, GLsizei n, const GLuint* fences);
extern void (*GL_TH_FN(glGenFencesNV))(GL_TH_DP, GLsizei n, GLuint* fences);
extern GLboolean (*GL_TH_FN(glIsFenceNV))(GL_TH_DP, GLuint fence);
extern GLboolean (*GL_TH_FN(glTestFenceNV))(GL_TH_DP, GLuint fence);
extern void (*GL_TH_FN(glGetFenceivNV))(GL_TH_DP, GLuint fence, GLenum pname, GLint* params);
extern void (*GL_TH_FN(glFinishFenceNV))(GL_TH_DP, GLuint fence);
extern void (*GL_TH_FN(glSetFenceNV))(GL_TH_DP, GLuint a, GLenum b);
extern void (*GL_TH_FN(glGetDriverControlsQCOM))(GL_TH_DP, GLint* num, GLsizei size, GLuint* driverControls);
extern void (*GL_TH_FN(glGetDriverControlStringQCOM))(GL_TH_DP, GLuint driverControl, GLsizei bufSize, GLsizei* length, char* driverControlString);
extern void (*GL_TH_FN(glEnableDriverControlQCOM))(GL_TH_DP, GLuint driverControl);
extern void (*GL_TH_FN(glDisableDriverControlQCOM))(GL_TH_DP, GLuint driverControl);
extern void (*GL_TH_FN(glExtGetTexturesQCOM))(GL_TH_DP, GLuint* textures, GLint maxTextures, GLint* numTextures);
extern void (*GL_TH_FN(glExtGetBuffersQCOM))(GL_TH_DP, GLuint* buffers, GLint maxBuffers, GLint* numBuffers);
extern void (*GL_TH_FN(glExtGetRenderbuffersQCOM))(GL_TH_DP, GLuint* renderbuffers, GLint maxRenderbuffers, GLint* numRenderbuffers);
extern void (*GL_TH_FN(glExtGetFramebuffersQCOM))(GL_TH_DP, GLuint* framebuffers, GLint maxFramebuffers, GLint* numFramebuffers);
extern void (*GL_TH_FN(glExtGetTexLevelParameterivQCOM))(GL_TH_DP, GLuint texture, GLenum face, GLint level, GLenum pname, GLint* params);
extern void (*GL_TH_FN(glExtTexObjectStateOverrideiQCOM))(GL_TH_DP, GLenum target, GLenum pname, GLint param);
extern void (*GL_TH_FN(glExtGetTexSubImageQCOM))(GL_TH_DP, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, void* texels);
extern void (*GL_TH_FN(glExtGetBufferPointervQCOM))(GL_TH_DP, GLenum target, void** params);
extern void (*GL_TH_FN(glExtGetShadersQCOM))(GL_TH_DP, GLuint* shaders, GLint maxShaders, GLint* numShaders);
extern void (*GL_TH_FN(glExtGetProgramsQCOM))(GL_TH_DP, GLuint* programs, GLint maxPrograms, GLint* numPrograms);
extern GLboolean (*GL_TH_FN(glExtIsProgramBinaryQCOM))(GL_TH_DP, GLuint program);
extern void (*GL_TH_FN(glExtGetProgramBinarySourceQCOM))(GL_TH_DP, GLuint program, GLenum shadertype, char* source, GLint* length);
#ifndef GL_GLES
extern void (*GL_TH_FN(glAlphaFunc))(GL_TH_DP, GLenum func, GLclampf ref);
#endif
extern void (*GL_TH_FN(glClipPlanef))(GL_TH_DP, GLenum plane, const GLfloat *equation);
extern void (*GL_TH_FN(glColor4f))(GL_TH_DP, GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void (*GL_TH_FN(glFogf))(GL_TH_DP, GLenum pname, GLfloat param);
extern void (*GL_TH_FN(glFogfv))(GL_TH_DP, GLenum pname, const GLfloat *params);
extern void (*GL_TH_FN(glFrustumf))(GL_TH_DP, GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar);
extern void (*GL_TH_FN(glGetClipPlanef))(GL_TH_DP, GLenum pname, GLfloat eqn[4]);
extern void (*GL_TH_FN(glGetLightfv))(GL_TH_DP, GLenum light, GLenum pname, GLfloat *params);
extern void (*GL_TH_FN(glGetMaterialfv))(GL_TH_DP, GLenum face, GLenum pname, GLfloat *params);
extern void (*GL_TH_FN(glGetTexEnvfv))(GL_TH_DP, GLenum env, GLenum pname, GLfloat *params);
extern void (*GL_TH_FN(glLightModelf))(GL_TH_DP, GLenum pname, GLfloat param);
extern void (*GL_TH_FN(glLightModelfv))(GL_TH_DP, GLenum pname, const GLfloat *params);
extern void (*GL_TH_FN(glLightf))(GL_TH_DP, GLenum light, GLenum pname, GLfloat param);
extern void (*GL_TH_FN(glLightfv))(GL_TH_DP, GLenum light, GLenum pname, const GLfloat *params);
extern void (*GL_TH_FN(glLoadMatrixf))(GL_TH_DP, const GLfloat *m);
extern void (*GL_TH_FN(glMaterialf))(GL_TH_DP, GLenum face, GLenum pname, GLfloat param);
extern void (*GL_TH_FN(glMaterialfv))(GL_TH_DP, GLenum face, GLenum pname, const GLfloat *params);
extern void (*GL_TH_FN(glMultMatrixf))(GL_TH_DP, const GLfloat *m);
extern void (*GL_TH_FN(glMultiTexCoord4f))(GL_TH_DP, GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q);
extern void (*GL_TH_FN(glNormal3f))(GL_TH_DP, GLfloat nx, GLfloat ny, GLfloat nz);
extern void (*GL_TH_FN(glOrthof))(GL_TH_DP, GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar);
extern void (*GL_TH_FN(glPointParameterf))(GL_TH_DP, GLenum pname, GLfloat param);
extern void (*GL_TH_FN(glPointParameterfv))(GL_TH_DP, GLenum pname, const GLfloat *params);
extern void (*GL_TH_FN(glPointSize))(GL_TH_DP, GLfloat size);
extern void (*GL_TH_FN(glPointSizePointerOES))(GL_TH_DP, GLenum type, GLsizei stride, const GLvoid * pointer);
extern void (*GL_TH_FN(glRotatef))(GL_TH_DP, GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
extern void (*GL_TH_FN(glScalef))(GL_TH_DP, GLfloat x, GLfloat y, GLfloat z);
extern void (*GL_TH_FN(glTexEnvf))(GL_TH_DP, GLenum target, GLenum pname, GLfloat param);
extern void (*GL_TH_FN(glTexEnvfv))(GL_TH_DP, GLenum target, GLenum pname, const GLfloat *params);
extern void (*GL_TH_FN(glTranslatef))(GL_TH_DP, GLfloat x, GLfloat y, GLfloat z);
extern void (*GL_TH_FN(glAlphaFuncx))(GL_TH_DP, GLenum func, GLclampx ref);
extern void (*GL_TH_FN(glClearColorx))(GL_TH_DP, GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha);
extern void (*GL_TH_FN(glClearDepthx))(GL_TH_DP, GLclampx depth);
extern void (*GL_TH_FN(glClientActiveTexture))(GL_TH_DP, GLenum texture);
extern void (*GL_TH_FN(glClipPlanex))(GL_TH_DP, GLenum plane, const GLfixed *equation);
extern void (*GL_TH_FN(glColor4ub))(GL_TH_DP, GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
extern void (*GL_TH_FN(glColor4x))(GL_TH_DP, GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha);
extern void (*GL_TH_FN(glColorPointer))(GL_TH_DP, GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
extern void (*GL_TH_FN(glDepthRangex))(GL_TH_DP, GLclampx zNear, GLclampx zFar);
extern void (*GL_TH_FN(glDisableClientState))(GL_TH_DP, GLenum array);
extern void (*GL_TH_FN(glEnableClientState))(GL_TH_DP, GLenum array);
extern void (*GL_TH_FN(glFogx))(GL_TH_DP, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glFogxv))(GL_TH_DP, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glFrustumx))(GL_TH_DP, GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar);
extern void (*GL_TH_FN(glGetClipPlanex))(GL_TH_DP, GLenum pname, GLfixed eqn[4]);
extern void (*GL_TH_FN(glGetFixedv))(GL_TH_DP, GLenum pname, GLfixed *params);
extern void (*GL_TH_FN(glGetLightxv))(GL_TH_DP, GLenum light, GLenum pname, GLfixed *params);
extern void (*GL_TH_FN(glGetMaterialxv))(GL_TH_DP, GLenum face, GLenum pname, GLfixed *params);
extern void (*GL_TH_FN(glGetPointerv))(GL_TH_DP, GLenum pname, GLvoid **params);
extern void (*GL_TH_FN(glGetTexEnviv))(GL_TH_DP, GLenum env, GLenum pname, GLint *params);
extern void (*GL_TH_FN(glGetTexEnvxv))(GL_TH_DP, GLenum env, GLenum pname, GLfixed *params);
extern void (*GL_TH_FN(glGetTexParameterxv))(GL_TH_DP, GLenum target, GLenum pname, GLfixed *params);
extern void (*GL_TH_FN(glLightModelx))(GL_TH_DP, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glLightModelxv))(GL_TH_DP, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glLightx))(GL_TH_DP, GLenum light, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glLightxv))(GL_TH_DP, GLenum light, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glLineWidthx))(GL_TH_DP, GLfixed width);
extern void (*GL_TH_FN(glLoadIdentity))(GL_TH_DP);
extern void (*GL_TH_FN(glLoadMatrixx))(GL_TH_DP, const GLfixed *m);
extern void (*GL_TH_FN(glLogicOp))(GL_TH_DP, GLenum opcode);
extern void (*GL_TH_FN(glMaterialx))(GL_TH_DP, GLenum face, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glMaterialxv))(GL_TH_DP, GLenum face, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glMatrixMode))(GL_TH_DP, GLenum mode);
extern void (*GL_TH_FN(glMultMatrixx))(GL_TH_DP, const GLfixed *m);
extern void (*GL_TH_FN(glMultiTexCoord4x))(GL_TH_DP, GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q);
extern void (*GL_TH_FN(glNormal3x))(GL_TH_DP, GLfixed nx, GLfixed ny, GLfixed nz);
extern void (*GL_TH_FN(glNormalPointer))(GL_TH_DP, GLenum type, GLsizei stride, const GLvoid *pointer);
extern void (*GL_TH_FN(glOrthox))(GL_TH_DP, GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar);
extern void (*GL_TH_FN(glPointParameterx))(GL_TH_DP, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glPointParameterxv))(GL_TH_DP, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glPointSizex))(GL_TH_DP, GLfixed size);
extern void (*GL_TH_FN(glPolygonOffsetx))(GL_TH_DP, GLfixed factor, GLfixed units);
extern void (*GL_TH_FN(glPopMatrix))(GL_TH_DP);
extern void (*GL_TH_FN(glPushMatrix))(GL_TH_DP);
extern void (*GL_TH_FN(glRotatex))(GL_TH_DP, GLfixed angle, GLfixed x, GLfixed y, GLfixed z);
extern void (*GL_TH_FN(glSampleCoveragex))(GL_TH_DP, GLclampx value, GLboolean invert);
extern void (*GL_TH_FN(glScalex))(GL_TH_DP, GLfixed x, GLfixed y, GLfixed z);
extern void (*GL_TH_FN(glShadeModel))(GL_TH_DP, GLenum mode);
extern void (*GL_TH_FN(glTexCoordPointer))(GL_TH_DP, GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
extern void (*GL_TH_FN(glTexEnvi))(GL_TH_DP, GLenum target, GLenum pname, GLint param);
extern void (*GL_TH_FN(glTexEnvx))(GL_TH_DP, GLenum target, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glTexEnviv))(GL_TH_DP, GLenum target, GLenum pname, const GLint *params);
extern void (*GL_TH_FN(glTexEnvxv))(GL_TH_DP, GLenum target, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glTexParameterx))(GL_TH_DP, GLenum target, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glTexParameterxv))(GL_TH_DP, GLenum target, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glTranslatex))(GL_TH_DP, GLfixed x, GLfixed y, GLfixed z);
extern void (*GL_TH_FN(glVertexPointer))(GL_TH_DP, GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
extern void (*GL_TH_FN(glBlendEquationSeparateOES))(GL_TH_DP, GLenum modeRGB, GLenum modeAlpha);
extern void (*GL_TH_FN(glBlendFuncSeparateOES))(GL_TH_DP, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
extern void (*GL_TH_FN(glBlendEquationOES))(GL_TH_DP, GLenum mode);
extern void (*GL_TH_FN(glDrawTexsOES))(GL_TH_DP, GLshort x, GLshort y, GLshort z, GLshort width, GLshort height);
extern void (*GL_TH_FN(glDrawTexiOES))(GL_TH_DP, GLint x, GLint y, GLint z, GLint width, GLint height);
extern void (*GL_TH_FN(glDrawTexxOES))(GL_TH_DP, GLfixed x, GLfixed y, GLfixed z, GLfixed width, GLfixed height);
extern void (*GL_TH_FN(glDrawTexsvOES))(GL_TH_DP, const GLshort *coords);
extern void (*GL_TH_FN(glDrawTexivOES))(GL_TH_DP, const GLint *coords);
extern void (*GL_TH_FN(glDrawTexxvOES))(GL_TH_DP, const GLfixed *coords);
extern void (*GL_TH_FN(glDrawTexfOES))(GL_TH_DP, GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height);
extern void (*GL_TH_FN(glDrawTexfvOES))(GL_TH_DP, const GLfloat *coords);
extern void (*GL_TH_FN(glAlphaFuncxOES))(GL_TH_DP, GLenum func, GLclampx ref);
extern void (*GL_TH_FN(glClearColorxOES))(GL_TH_DP, GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha);
extern void (*GL_TH_FN(glClearDepthxOES))(GL_TH_DP, GLclampx depth);
extern void (*GL_TH_FN(glClipPlanexOES))(GL_TH_DP, GLenum plane, const GLfixed *equation);
extern void (*GL_TH_FN(glColor4xOES))(GL_TH_DP, GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha);
extern void (*GL_TH_FN(glDepthRangexOES))(GL_TH_DP, GLclampx zNear, GLclampx zFar);
extern void (*GL_TH_FN(glFogxOES))(GL_TH_DP, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glFogxvOES))(GL_TH_DP, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glFrustumxOES))(GL_TH_DP, GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar);
extern void (*GL_TH_FN(glGetClipPlanexOES))(GL_TH_DP, GLenum pname, GLfixed eqn[4]);
extern void (*GL_TH_FN(glGetFixedvOES))(GL_TH_DP, GLenum pname, GLfixed *params);
extern void (*GL_TH_FN(glGetLightxvOES))(GL_TH_DP, GLenum light, GLenum pname, GLfixed *params);
extern void (*GL_TH_FN(glGetMaterialxvOES))(GL_TH_DP, GLenum face, GLenum pname, GLfixed *params);
extern void (*GL_TH_FN(glGetTexEnvxvOES))(GL_TH_DP, GLenum env, GLenum pname, GLfixed *params);
extern void (*GL_TH_FN(glGetTexParameterxvOES))(GL_TH_DP, GLenum target, GLenum pname, GLfixed *params);
extern void (*GL_TH_FN(glLightModelxOES))(GL_TH_DP, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glLightModelxvOES))(GL_TH_DP, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glLightxOES))(GL_TH_DP, GLenum light, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glLightxvOES))(GL_TH_DP, GLenum light, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glLineWidthxOES))(GL_TH_DP, GLfixed width);
extern void (*GL_TH_FN(glLoadMatrixxOES))(GL_TH_DP, const GLfixed *m);
extern void (*GL_TH_FN(glMaterialxOES))(GL_TH_DP, GLenum face, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glMaterialxvOES))(GL_TH_DP, GLenum face, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glMultMatrixxOES))(GL_TH_DP, const GLfixed *m);
extern void (*GL_TH_FN(glMultiTexCoord4xOES))(GL_TH_DP, GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q);
extern void (*GL_TH_FN(glNormal3xOES))(GL_TH_DP, GLfixed nx, GLfixed ny, GLfixed nz);
extern void (*GL_TH_FN(glOrthoxOES))(GL_TH_DP, GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar);
extern void (*GL_TH_FN(glPointParameterxOES))(GL_TH_DP, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glPointParameterxvOES))(GL_TH_DP, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glPointSizexOES))(GL_TH_DP, GLfixed size);
extern void (*GL_TH_FN(glPolygonOffsetxOES))(GL_TH_DP, GLfixed factor, GLfixed units);
extern void (*GL_TH_FN(glRotatexOES))(GL_TH_DP, GLfixed angle, GLfixed x, GLfixed y, GLfixed z);
extern void (*GL_TH_FN(glSampleCoveragexOES))(GL_TH_DP, GLclampx value, GLboolean invert);
extern void (*GL_TH_FN(glScalexOES))(GL_TH_DP, GLfixed x, GLfixed y, GLfixed z);
extern void (*GL_TH_FN(glTexEnvxOES))(GL_TH_DP, GLenum target, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glTexEnvxvOES))(GL_TH_DP, GLenum target, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glTexParameterxOES))(GL_TH_DP, GLenum target, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glTexParameterxvOES))(GL_TH_DP, GLenum target, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glTranslatexOES))(GL_TH_DP, GLfixed x, GLfixed y, GLfixed z);
extern GLboolean (*GL_TH_FN(glIsRenderbufferOES))(GL_TH_DP, GLuint renderbuffer);
extern void (*GL_TH_FN(glBindRenderbufferOES))(GL_TH_DP, GLenum target, GLuint renderbuffer);
extern void (*GL_TH_FN(glDeleteRenderbuffersOES))(GL_TH_DP, GLsizei n, const GLuint* renderbuffers);
extern void (*GL_TH_FN(glGenRenderbuffersOES))(GL_TH_DP, GLsizei n, GLuint* renderbuffers);
extern void (*GL_TH_FN(glRenderbufferStorageOES))(GL_TH_DP, GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
extern void (*GL_TH_FN(glGetRenderbufferParameterivOES))(GL_TH_DP, GLenum target, GLenum pname, GLint* params);
extern GLboolean (*GL_TH_FN(glIsFramebufferOES))(GL_TH_DP, GLuint framebuffer);
extern void (*GL_TH_FN(glBindFramebufferOES))(GL_TH_DP, GLenum target, GLuint framebuffer);
extern void (*GL_TH_FN(glDeleteFramebuffersOES))(GL_TH_DP, GLsizei n, const GLuint* framebuffers);
extern void (*GL_TH_FN(glGenFramebuffersOES))(GL_TH_DP, GLsizei n, GLuint* framebuffers);
extern GLenum (*GL_TH_FN(glCheckFramebufferStatusOES))(GL_TH_DP, GLenum target);
extern void (*GL_TH_FN(glFramebufferRenderbufferOES))(GL_TH_DP, GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
extern void (*GL_TH_FN(glFramebufferTexture2DOES))(GL_TH_DP, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
extern void (*GL_TH_FN(glGetFramebufferAttachmentParameterivOES))(GL_TH_DP, GLenum target, GLenum attachment, GLenum pname, GLint* params);
extern void (*GL_TH_FN(glGenerateMipmapOES))(GL_TH_DP, GLenum target);
extern void (*GL_TH_FN(glCurrentPaletteMatrixOES))(GL_TH_DP, GLuint matrixpaletteindex);
extern void (*GL_TH_FN(glLoadPaletteFromModelViewMatrixOES))(GL_TH_DP);
extern void (*GL_TH_FN(glMatrixIndexPointerOES))(GL_TH_DP, GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
extern void (*GL_TH_FN(glWeightPointerOES))(GL_TH_DP, GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
extern GLbitfield (*GL_TH_FN(glQueryMatrixxOES))(GL_TH_DP, GLfixed mantissa[16], GLint exponent[16]);
extern void (*GL_TH_FN(glDepthRangefOES))(GL_TH_DP, GLclampf zNear, GLclampf zFar);
extern void (*GL_TH_FN(glFrustumfOES))(GL_TH_DP, GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar);
extern void (*GL_TH_FN(glOrthofOES))(GL_TH_DP, GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar);
extern void (*GL_TH_FN(glClipPlanefOES))(GL_TH_DP, GLenum plane, const GLfloat *equation);
extern void (*GL_TH_FN(glGetClipPlanefOES))(GL_TH_DP, GLenum pname, GLfloat eqn[4]);
extern void (*GL_TH_FN(glClearDepthfOES))(GL_TH_DP, GLclampf depth);
extern void (*GL_TH_FN(glTexGenfOES))(GL_TH_DP, GLenum coord, GLenum pname, GLfloat param);
extern void (*GL_TH_FN(glTexGenfvOES))(GL_TH_DP, GLenum coord, GLenum pname, const GLfloat *params);
extern void (*GL_TH_FN(glTexGeniOES))(GL_TH_DP, GLenum coord, GLenum pname, GLint param);
extern void (*GL_TH_FN(glTexGenivOES))(GL_TH_DP, GLenum coord, GLenum pname, const GLint *params);
extern void (*GL_TH_FN(glTexGenxOES))(GL_TH_DP, GLenum coord, GLenum pname, GLfixed param);
extern void (*GL_TH_FN(glTexGenxvOES))(GL_TH_DP, GLenum coord, GLenum pname, const GLfixed *params);
extern void (*GL_TH_FN(glGetTexGenfvOES))(GL_TH_DP, GLenum coord, GLenum pname, GLfloat *params);
extern void (*GL_TH_FN(glGetTexGenivOES))(GL_TH_DP, GLenum coord, GLenum pname, GLint *params);
extern void (*GL_TH_FN(glGetTexGenxvOES))(GL_TH_DP, GLenum coord, GLenum pname, GLfixed *params);
extern void (*GL_TH_FN(glBindVertexArrayOES))(GL_TH_DP, GLuint array);
extern void (*GL_TH_FN(glDeleteVertexArraysOES))(GL_TH_DP, GLsizei n, const GLuint *arrays);
extern void (*GL_TH_FN(glGenVertexArraysOES))(GL_TH_DP, GLsizei n, GLuint *arrays);
extern GLboolean (*GL_TH_FN(glIsVertexArrayOES))(GL_TH_DP, GLuint array);
extern void (*GL_TH_FN(glCopyTextureLevelsAPPLE))(GL_TH_DP, GLuint destinationTexture, GLuint sourceTexture, GLint sourceBaseLevel, GLsizei sourceLevelCount);
extern void (*GL_TH_FN(glRenderbufferStorageMultisampleAPPLE))(GL_TH_DP, GLenum a, GLsizei b, GLenum c, GLsizei d, GLsizei e);
extern void (*GL_TH_FN(glResolveMultisampleFramebufferAPPLE))(GL_TH_DP);
extern GLsync (*GL_TH_FN(glFenceSyncAPPLE))(GL_TH_DP, GLenum condition, GLbitfield flags);
extern GLboolean (*GL_TH_FN(glIsSyncAPPLE))(GL_TH_DP, GLsync sync);
extern void (*GL_TH_FN(glDeleteSyncAPPLE))(GL_TH_DP, GLsync sync);
extern GLenum (*GL_TH_FN(glClientWaitSyncAPPLE))(GL_TH_DP, GLsync sync, GLbitfield flags, EvasGLuint64 timeout);
extern void (*GL_TH_FN(glWaitSyncAPPLE))(GL_TH_DP, GLsync sync, GLbitfield flags, EvasGLuint64 timeout);
extern void (*GL_TH_FN(glGetInteger64vAPPLE))(GL_TH_DP, GLenum pname, EvasGLint64 *params);
extern void (*GL_TH_FN(glGetSyncivAPPLE))(GL_TH_DP, GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values);
extern void * (*GL_TH_FN(glMapBufferRangeEXT))(GL_TH_DP, GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
extern void (*GL_TH_FN(glFlushMappedBufferRangeEXT))(GL_TH_DP, GLenum target, GLintptr offset, GLsizeiptr length);
extern void (*GL_TH_FN(glRenderbufferStorageMultisampleEXT))(GL_TH_DP, GLenum a, GLsizei b, GLenum c, GLsizei d, GLsizei e);
extern void (*GL_TH_FN(glFramebufferTexture2DMultisampleEXT))(GL_TH_DP, GLenum a, GLenum b, GLenum c, GLuint d, GLint e, GLsizei f);
extern GLenum (*GL_TH_FN(glGetGraphicsResetStatusEXT))(GL_TH_DP);
extern void (*GL_TH_FN(glReadnPixelsEXT))(GL_TH_DP, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data);
extern void (*GL_TH_FN(glGetnUniformfvEXT))(GL_TH_DP, GLuint program, GLint location, GLsizei bufSize, float *params);
extern void (*GL_TH_FN(glGetnUniformivEXT))(GL_TH_DP, GLuint program, GLint location, GLsizei bufSize, GLint *params);
extern void (*GL_TH_FN(glTexStorage1DEXT))(GL_TH_DP, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width);
extern void (*GL_TH_FN(glTexStorage2DEXT))(GL_TH_DP, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
extern void (*GL_TH_FN(glTexStorage3DEXT))(GL_TH_DP, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
extern void (*GL_TH_FN(glTextureStorage1DEXT))(GL_TH_DP, GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width);
extern void (*GL_TH_FN(glTextureStorage2DEXT))(GL_TH_DP, GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
extern void (*GL_TH_FN(glTextureStorage3DEXT))(GL_TH_DP, GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
extern void (*GL_TH_FN(glClipPlanefIMG))(GL_TH_DP, GLenum a, const GLfloat * b);
extern void (*GL_TH_FN(glClipPlanexIMG))(GL_TH_DP, GLenum a, const GLfixed * b);
extern void (*GL_TH_FN(glRenderbufferStorageMultisampleIMG))(GL_TH_DP, GLenum a, GLsizei b, GLenum c, GLsizei d, GLsizei e);
extern void (*GL_TH_FN(glFramebufferTexture2DMultisampleIMG))(GL_TH_DP, GLenum a, GLenum b, GLenum c, GLuint d, GLint e, GLsizei f);
extern void (*GL_TH_FN(glActivateTile))(GL_TH_DP, GLuint a, GLuint b, GLuint c, GLuint d, GLuint e);
extern void (*GL_TH_FN(glStartTilingQCOM))(GL_TH_DP, GLuint x, GLuint y, GLuint width, GLuint height, GLbitfield preserveMask);
extern void (*GL_TH_FN(glEndTilingQCOM))(GL_TH_DP, GLbitfield preserveMask);
extern void (*GL_TH_FN(glBeginQuery))(GL_TH_DP, GLenum target, GLuint id);
extern void (*GL_TH_FN(glBeginTransformFeedback))(GL_TH_DP, GLenum primitiveMode);
extern void (*GL_TH_FN(glBindBufferBase))(GL_TH_DP, GLenum target, GLuint index, GLuint buffer);
extern void (*GL_TH_FN(glBindBufferRange))(GL_TH_DP, GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
extern void (*GL_TH_FN(glBindSampler))(GL_TH_DP, GLuint unit, GLuint sampler);
extern void (*GL_TH_FN(glBindTransformFeedback))(GL_TH_DP, GLenum target, GLuint id);
extern void (*GL_TH_FN(glBindVertexArray))(GL_TH_DP, GLuint array);
extern void (*GL_TH_FN(glBlitFramebuffer))(GL_TH_DP, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
extern void (*GL_TH_FN(glClearBufferfi))(GL_TH_DP, GLenum buffer, GLint drawBuffer, GLfloat depth, GLint stencil);
extern void (*GL_TH_FN(glClearBufferfv))(GL_TH_DP, GLenum buffer, GLint drawBuffer, const GLfloat * value);
extern void (*GL_TH_FN(glClearBufferiv))(GL_TH_DP, GLenum buffer, GLint drawBuffer, const GLint * value);
extern void (*GL_TH_FN(glClearBufferuiv))(GL_TH_DP, GLenum buffer, GLint drawBuffer, const GLuint * value);
extern GLenum (*GL_TH_FN(glClientWaitSync))(GL_TH_DP, GLsync sync, GLbitfield flags, EvasGLuint64 timeout);
extern void (*GL_TH_FN(glCompressedTexImage3D))(GL_TH_DP, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid * data);
extern void (*GL_TH_FN(glCompressedTexSubImage3D))(GL_TH_DP, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data);
extern void (*GL_TH_FN(glCopyBufferSubData))(GL_TH_DP, GLenum readtarget, GLenum writetarget, GLintptr readoffset, GLintptr writeoffset, GLsizeiptr size);
extern void (*GL_TH_FN(glCopyTexSubImage3D))(GL_TH_DP, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern void (*GL_TH_FN(glDeleteQueries))(GL_TH_DP, GLsizei n, const GLuint * ids);
extern void (*GL_TH_FN(glDeleteSamplers))(GL_TH_DP, GLsizei n, const GLuint * samplers);
extern void (*GL_TH_FN(glDeleteSync))(GL_TH_DP, GLsync sync);
extern void (*GL_TH_FN(glDeleteTransformFeedbacks))(GL_TH_DP, GLsizei n, const GLuint *ids);
extern void (*GL_TH_FN(glDeleteVertexArrays))(GL_TH_DP, GLsizei n, const GLuint *arrays);
extern void (*GL_TH_FN(glDrawArraysInstanced))(GL_TH_DP, GLenum mode, GLint first, GLsizei count, GLsizei primcount);
extern void (*GL_TH_FN(glDrawBuffers))(GL_TH_DP, GLsizei n, const GLenum *bufs);
extern void (*GL_TH_FN(glDrawElementsInstanced))(GL_TH_DP, GLenum mode, GLsizei count, GLenum type, const void * indices, GLsizei primcount);
extern void (*GL_TH_FN(glDrawRangeElements))(GL_TH_DP, GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices);
extern void (*GL_TH_FN(glEndQuery))(GL_TH_DP, GLenum target);
extern void (*GL_TH_FN(glEndTransformFeedback))(GL_TH_DP);
extern GLsync (*GL_TH_FN(glFenceSync))(GL_TH_DP, GLenum condition, GLbitfield flags);
extern GLsync (*GL_TH_FN(glFlushMappedBufferRange))(GL_TH_DP, GLenum target, GLintptr offset, GLsizeiptr length);
extern void (*GL_TH_FN(glFramebufferTextureLayer))(GL_TH_DP, GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
extern void (*GL_TH_FN(glGenQueries))(GL_TH_DP, GLsizei n, GLuint * ids);
extern void (*GL_TH_FN(glGenSamplers))(GL_TH_DP, GLsizei n, GLuint *samplers);
extern void (*GL_TH_FN(glGenTransformFeedbacks))(GL_TH_DP, GLsizei n, GLuint *ids);
extern void (*GL_TH_FN(glGenVertexArrays))(GL_TH_DP, GLsizei n, GLuint *arrays);
extern void (*GL_TH_FN(glGetActiveUniformBlockiv))(GL_TH_DP, GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params);
extern void (*GL_TH_FN(glGetActiveUniformBlockName))(GL_TH_DP, GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName);
extern void (*GL_TH_FN(glGetActiveUniformsiv))(GL_TH_DP, GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params);
extern void (*GL_TH_FN(glGetBufferParameteri64v))(GL_TH_DP, GLenum target, GLenum value, EvasGLint64 * data);
extern void (*GL_TH_FN(glGetBufferPointerv))(GL_TH_DP, GLenum target, GLenum pname, GLvoid ** params);
extern GLint (*GL_TH_FN(glGetFragDataLocation))(GL_TH_DP, GLuint program, const char * name);
extern void (*GL_TH_FN(glGetInteger64i_v))(GL_TH_DP, GLenum target, GLuint index, EvasGLint64 * data);
extern void (*GL_TH_FN(glGetInteger64v))(GL_TH_DP, GLenum pname, EvasGLint64 * data);
extern void (*GL_TH_FN(glGetIntegeri_v))(GL_TH_DP, GLenum target, GLuint index, GLint * data);
extern void (*GL_TH_FN(glGetInternalformativ))(GL_TH_DP, GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint *params);
extern void (*GL_TH_FN(glGetProgramBinary))(GL_TH_DP, GLuint program, GLsizei bufsize, GLsizei *length, GLenum *binaryFormat, void *binary);
extern void (*GL_TH_FN(glGetQueryiv))(GL_TH_DP, GLenum target, GLenum pname, GLint * params);
extern void (*GL_TH_FN(glGetQueryObjectuiv))(GL_TH_DP, GLuint id, GLenum pname, GLuint * params);
extern void (*GL_TH_FN(glGetSamplerParameterfv))(GL_TH_DP, GLuint sampler, GLenum pname, GLfloat * params);
extern void (*GL_TH_FN(glGetSamplerParameteriv))(GL_TH_DP, GLuint sampler, GLenum pname, GLint * params);
extern const GLubyte * (*GL_TH_FN(glGetStringi))(GL_TH_DP, GLenum name, GLuint index);
extern void (*GL_TH_FN(glGetSynciv))(GL_TH_DP, GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values);
extern void (*GL_TH_FN(glGetTransformFeedbackVarying))(GL_TH_DP, GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLsizei * size, GLenum * type, char * name);
extern GLuint (*GL_TH_FN(glGetUniformBlockIndex))(GL_TH_DP, GLuint program, const GLchar *uniformBlockName);
extern void (*GL_TH_FN(glGetUniformIndices))(GL_TH_DP, GLuint program, GLsizei uniformCount, const GLchar *const*uniformNames, GLuint *uniformIndices);
extern void (*GL_TH_FN(glGetUniformuiv))(GL_TH_DP, GLuint program, GLint location, GLuint* params);
extern void (*GL_TH_FN(glGetVertexAttribIiv))(GL_TH_DP, GLuint index, GLenum pname, GLint *params);
extern void (*GL_TH_FN(glGetVertexAttribIuiv))(GL_TH_DP, GLuint index, GLenum pname, GLuint *params);
extern void (*GL_TH_FN(glInvalidateFramebuffer))(GL_TH_DP, GLenum target, GLsizei numAttachments, const GLenum *attachments);
extern void (*GL_TH_FN(glInvalidateSubFramebuffer))(GL_TH_DP, GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height);
extern GLboolean (*GL_TH_FN(glIsQuery))(GL_TH_DP, GLuint id);
extern GLboolean (*GL_TH_FN(glIsSampler))(GL_TH_DP, GLuint id);
extern GLboolean (*GL_TH_FN(glIsSync))(GL_TH_DP, GLsync sync);
extern GLboolean (*GL_TH_FN(glIsTransformFeedback))(GL_TH_DP, GLuint id);
extern GLboolean (*GL_TH_FN(glIsVertexArray))(GL_TH_DP, GLuint array);
extern void * (*GL_TH_FN(glMapBufferRange))(GL_TH_DP, GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
extern void (*GL_TH_FN(glPauseTransformFeedback))(GL_TH_DP);
extern void (*GL_TH_FN(glProgramBinary))(GL_TH_DP, GLuint program, GLenum binaryFormat, const void *binary, GLsizei length);
extern void (*GL_TH_FN(glProgramParameteri))(GL_TH_DP, GLuint program, GLenum pname, GLint value);
extern void (*GL_TH_FN(glReadBuffer))(GL_TH_DP, GLenum src);
#ifndef GL_GLES
extern void (*GL_TH_FN(glRenderbufferStorageMultisample))(GL_TH_DP, GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
#endif
extern void (*GL_TH_FN(glResumeTransformFeedback))(GL_TH_DP);
extern void (*GL_TH_FN(glSamplerParameterf))(GL_TH_DP, GLuint sampler, GLenum pname, GLfloat param);
extern void (*GL_TH_FN(glSamplerParameterfv))(GL_TH_DP, GLuint sampler, GLenum pname, const GLfloat * params);
extern void (*GL_TH_FN(glSamplerParameteri))(GL_TH_DP, GLuint sampler, GLenum pname, GLint param);
extern void (*GL_TH_FN(glSamplerParameteriv))(GL_TH_DP, GLuint sampler, GLenum pname, const GLint * params);
extern void (*GL_TH_FN(glTexImage3D))(GL_TH_DP, GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * data);
extern void (*GL_TH_FN(glTexStorage2D))(GL_TH_DP, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
extern void (*GL_TH_FN(glTexStorage3D))(GL_TH_DP, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
extern void (*GL_TH_FN(glTexSubImage3D))(GL_TH_DP, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * data);
extern void (*GL_TH_FN(glTransformFeedbackVaryings))(GL_TH_DP, GLuint program, GLsizei count, const GLchar *const* varyings, GLenum bufferMode);
extern void (*GL_TH_FN(glUniform1ui))(GL_TH_DP, GLint location, GLuint v0);
extern void (*GL_TH_FN(glUniform1uiv))(GL_TH_DP, GLint location, GLsizei count, const GLuint *value);
extern void (*GL_TH_FN(glUniform2ui))(GL_TH_DP, GLint location, GLuint v0, GLuint v1);
extern void (*GL_TH_FN(glUniform2uiv))(GL_TH_DP, GLint location, GLsizei count, const GLuint *value);
extern void (*GL_TH_FN(glUniform3ui))(GL_TH_DP, GLint location, GLuint v0, GLuint v1, GLuint v2);
extern void (*GL_TH_FN(glUniform3uiv))(GL_TH_DP, GLint location, GLsizei count, const GLuint *value);
extern void (*GL_TH_FN(glUniform4ui))(GL_TH_DP, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
extern void (*GL_TH_FN(glUniform4uiv))(GL_TH_DP, GLint location, GLsizei count, const GLuint *value);
extern void (*GL_TH_FN(glUniformBlockBinding))(GL_TH_DP, GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
extern void (*GL_TH_FN(glUniformMatrix2x3fv))(GL_TH_DP, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glUniformMatrix3x2fv))(GL_TH_DP, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glUniformMatrix2x4fv))(GL_TH_DP, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glUniformMatrix4x2fv))(GL_TH_DP, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glUniformMatrix3x4fv))(GL_TH_DP, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glUniformMatrix4x3fv))(GL_TH_DP, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern GLboolean (*GL_TH_FN(glUnmapBuffer))(GL_TH_DP, GLenum target);
extern void (*GL_TH_FN(glVertexAttribDivisor))(GL_TH_DP, GLuint index, GLuint divisor);
extern void (*GL_TH_FN(glVertexAttribI4i))(GL_TH_DP, GLuint index, GLint v0, GLint v1, GLint v2, GLint v3);
extern void (*GL_TH_FN(glVertexAttribI4iv))(GL_TH_DP, GLuint index, const GLint *v);
extern void (*GL_TH_FN(glVertexAttribI4ui))(GL_TH_DP, GLuint index, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
extern void (*GL_TH_FN(glVertexAttribI4uiv))(GL_TH_DP, GLuint index, const GLuint *v);
extern void (*GL_TH_FN(glVertexAttribIPointer))(GL_TH_DP, GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
extern void (*GL_TH_FN(glWaitSync))(GL_TH_DP, GLsync sync, GLbitfield flags, EvasGLuint64 timeout);
extern void (*GL_TH_FN(glDispatchCompute))(GL_TH_DP, GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
extern void (*GL_TH_FN(glDispatchComputeIndirect))(GL_TH_DP, GLintptr indirect);
extern void (*GL_TH_FN(glDrawArraysIndirect))(GL_TH_DP, GLenum mode, const void *indirect);
extern void (*GL_TH_FN(glDrawElementsIndirect))(GL_TH_DP, GLenum mode, GLenum type, const void *indirect);
extern void (*GL_TH_FN(glFramebufferParameteri))(GL_TH_DP, GLenum target, GLenum pname, GLint param);
extern void (*GL_TH_FN(glGetFramebufferParameteriv))(GL_TH_DP, GLenum target, GLenum pname, GLint *params);
extern void (*GL_TH_FN(glGetProgramInterfaceiv))(GL_TH_DP, GLuint program, GLenum programInterface, GLenum pname, GLint *params);
extern GLuint (*GL_TH_FN(glGetProgramResourceIndex))(GL_TH_DP, GLuint program, GLenum programInterface, const GLchar *name);
extern void (*GL_TH_FN(glGetProgramResourceName))(GL_TH_DP, GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
extern void (*GL_TH_FN(glGetProgramResourceiv))(GL_TH_DP, GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei bufSize, GLsizei *length, GLint *params);
extern GLint (*GL_TH_FN(glGetProgramResourceLocation))(GL_TH_DP, GLuint program, GLenum programInterface, const GLchar *name);
extern void (*GL_TH_FN(glUseProgramStages))(GL_TH_DP, GLuint pipeline, GLbitfield stages, GLuint program);
extern void (*GL_TH_FN(glActiveShaderProgram))(GL_TH_DP, GLuint pipeline, GLuint program);
extern GLuint (*GL_TH_FN(glCreateShaderProgramv))(GL_TH_DP, GLenum type, GLsizei count, const GLchar *const*strings);
extern void (*GL_TH_FN(glBindProgramPipeline))(GL_TH_DP, GLuint pipeline);
extern void (*GL_TH_FN(glDeleteProgramPipelines))(GL_TH_DP, GLsizei n, const GLuint *pipelines);
extern void (*GL_TH_FN(glGenProgramPipelines))(GL_TH_DP, GLsizei n, GLuint *pipelines);
extern GLboolean (*GL_TH_FN(glIsProgramPipeline))(GL_TH_DP, GLuint pipeline);
extern void (*GL_TH_FN(glGetProgramPipelineiv))(GL_TH_DP, GLuint pipeline, GLenum pname, GLint *params);
extern void (*GL_TH_FN(glProgramUniform1i))(GL_TH_DP, GLuint program, GLint location, GLint v0);
extern void (*GL_TH_FN(glProgramUniform2i))(GL_TH_DP, GLuint program, GLint location, GLint v0, GLint v1);
extern void (*GL_TH_FN(glProgramUniform3i))(GL_TH_DP, GLuint program, GLint location, GLint v0, GLint v1, GLint v2);
extern void (*GL_TH_FN(glProgramUniform4i))(GL_TH_DP, GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
extern void (*GL_TH_FN(glProgramUniform1ui))(GL_TH_DP, GLuint program, GLint location, GLuint v0);
extern void (*GL_TH_FN(glProgramUniform2ui))(GL_TH_DP, GLuint program, GLint location, GLuint v0, GLuint v1);
extern void (*GL_TH_FN(glProgramUniform3ui))(GL_TH_DP, GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2);
extern void (*GL_TH_FN(glProgramUniform4ui))(GL_TH_DP, GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
extern void (*GL_TH_FN(glProgramUniform1f))(GL_TH_DP, GLuint program, GLint location, GLfloat v0);
extern void (*GL_TH_FN(glProgramUniform2f))(GL_TH_DP, GLuint program, GLint location, GLfloat v0, GLfloat v1);
extern void (*GL_TH_FN(glProgramUniform3f))(GL_TH_DP, GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
extern void (*GL_TH_FN(glProgramUniform4f))(GL_TH_DP, GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
extern void (*GL_TH_FN(glProgramUniform1iv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, const GLint *value);
extern void (*GL_TH_FN(glProgramUniform2iv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, const GLint *value);
extern void (*GL_TH_FN(glProgramUniform3iv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, const GLint *value);
extern void (*GL_TH_FN(glProgramUniform4iv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, const GLint *value);
extern void (*GL_TH_FN(glProgramUniform1uiv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, const GLuint *value);
extern void (*GL_TH_FN(glProgramUniform2uiv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, const GLuint *value);
extern void (*GL_TH_FN(glProgramUniform3uiv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, const GLuint *value);
extern void (*GL_TH_FN(glProgramUniform4uiv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, const GLuint *value);
extern void (*GL_TH_FN(glProgramUniform1fv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, const GLfloat *value);
extern void (*GL_TH_FN(glProgramUniform2fv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, const GLfloat *value);
extern void (*GL_TH_FN(glProgramUniform3fv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, const GLfloat *value);
extern void (*GL_TH_FN(glProgramUniform4fv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, const GLfloat *value);
extern void (*GL_TH_FN(glProgramUniformMatrix2fv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glProgramUniformMatrix3fv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glProgramUniformMatrix4fv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glProgramUniformMatrix2x3fv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glProgramUniformMatrix3x2fv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glProgramUniformMatrix2x4fv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glProgramUniformMatrix4x2fv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glProgramUniformMatrix3x4fv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glProgramUniformMatrix4x3fv))(GL_TH_DP, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*GL_TH_FN(glValidateProgramPipeline))(GL_TH_DP, GLuint pipeline);
extern void (*GL_TH_FN(glGetProgramPipelineInfoLog))(GL_TH_DP, GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
extern void (*GL_TH_FN(glBindImageTexture))(GL_TH_DP, GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
extern void (*GL_TH_FN(glGetBooleani_v))(GL_TH_DP, GLenum target, GLuint index, GLboolean *data);
extern void (*GL_TH_FN(glMemoryBarrier))(GL_TH_DP, GLbitfield barriers);
extern void (*GL_TH_FN(glMemoryBarrierByRegion))(GL_TH_DP, GLbitfield barriers);
extern void (*GL_TH_FN(glTexStorage2DMultisample))(GL_TH_DP, GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
extern void (*GL_TH_FN(glGetMultisamplefv))(GL_TH_DP, GLenum pname, GLuint index, GLfloat *val);
extern void (*GL_TH_FN(glSampleMaski))(GL_TH_DP, GLuint maskNumber, GLbitfield mask);
#ifndef GL_GLES
extern void (*GL_TH_FN(glGetTexLevelParameteriv))(GL_TH_DP, GLenum target, GLint level, GLenum pname, GLint *params);
#endif
extern void (*GL_TH_FN(glGetTexLevelParameterfv))(GL_TH_DP, GLenum target, GLint level, GLenum pname, GLfloat *params);
extern void (*GL_TH_FN(glBindVertexBuffer))(GL_TH_DP, GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
extern void (*GL_TH_FN(glVertexAttribFormat))(GL_TH_DP, GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
extern void (*GL_TH_FN(glVertexAttribIFormat))(GL_TH_DP, GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
extern void (*GL_TH_FN(glVertexAttribBinding))(GL_TH_DP, GLuint attribindex, GLuint bindingindex);
extern void (*GL_TH_FN(glVertexBindingDivisor))(GL_TH_DP, GLuint bindingindex, GLuint divisor);
extern void (*GL_TH_FN(glEGLImageTargetTexture2DOES))(GL_TH_DP, GLenum target, void *image);
extern void (*GL_TH_FN(glEGLImageTargetRenderbufferStorageOES))(GL_TH_DP, GLenum target, void *image);
extern EvasGLImage (*GL_TH_FN(evasglCreateImage))(GL_TH_DP, int target, void* buffer, const int *attrib_list);
extern void (*GL_TH_FN(evasglDestroyImage))(GL_TH_DP, EvasGLImage image);
extern EvasGLImage (*GL_TH_FN(evasglCreateImageForContext))(GL_TH_DP, Evas_GL *evas_gl, Evas_GL_Context *ctx, int target, void* buffer, const int *attrib_list);
extern EvasGLSync (*GL_TH_FN(evasglCreateSync))(GL_TH_DP, Evas_GL *evas_gl, unsigned int type, const int *attrib_list);
extern Eina_Bool (*GL_TH_FN(evasglDestroySync))(GL_TH_DP, Evas_GL *evas_gl, EvasGLSync sync);
extern int (*GL_TH_FN(evasglClientWaitSync))(GL_TH_DP, Evas_GL *evas_gl, EvasGLSync sync, int flags, EvasGLTime timeout);
extern Eina_Bool (*GL_TH_FN(evasglGetSyncAttrib))(GL_TH_DP, Evas_GL *evas_gl, EvasGLSync sync, int attribute, int *value);
extern Eina_Bool (*GL_TH_FN(evasglSignalSync))(GL_TH_DP, Evas_GL *evas_gl, EvasGLSync sync, unsigned mode);
extern int (*GL_TH_FN(evasglWaitSync))(GL_TH_DP, Evas_GL *evas_gl, EvasGLSync sync, int flags);
extern Eina_Bool (*GL_TH_FN(evasglBindWaylandDisplay))(GL_TH_DP, Evas_GL *evas_gl, void *wl_display);
extern Eina_Bool (*GL_TH_FN(evasglUnbindWaylandDisplay))(GL_TH_DP, Evas_GL *evas_gl, void *wl_display);
extern Eina_Bool (*GL_TH_FN(evasglQueryWaylandBuffer))(GL_TH_DP, Evas_GL *evas_gl, void *buffer, int attribute, int *value);

extern void _gl_thread_link_gl_generated_init(void *func_ptr);
