#!/bin/sh
rm -rf ./doc/html ./doc/latex ./doc/man
mkdir -p ./doc/html ./doc/latex ./doc/man 2>/dev/null
doxygen
cp doc/img/*.png doc/html/
cp doc/img/*.gif doc/html/
rm -f ecore_docs.tar ecore_docs.tar.gz
tar -cvf ecore_docs.tar doc/html doc/man doc/latex
gzip -9 ecore_docs.tar
exit 0
