#!/bin/sh
cp ./ecore.c.in ./ecore.c
for I in `find ./src/lib -name "Ecore*.h" -print`; do
  cat $I >> ./ecore.c
done
for I in `find ./src/lib -name "*.c" -print`; do
  cat $I >> ./ecore.c
done
rm -rf ./doc/html ./doc/latex ./doc/man
doxygen
cp doc/img/*.png doc/html/
rm -f ecore_docs.tar ecore_docs.tar.gz
tar -cvf ecore_docs.tar doc/html doc/man doc/latex
gzip -9 ecore_docs.tar
exit 0
