CC=gcc
COMMON_FLAGS=`pkg-config --libs --cflags eina,eet`

EXAMPLES= eet-basic \
          eet-data-cipher_decipher \
          eet-data-file_descriptor_01 \
          eet-data-file_descriptor_02 \
          eet-data-nested \
          eet-data-simple \
          eet-file

all: examples
examples: $(EXAMPLES)

$(EXAMPLES):
	$(CC) -o $@ $@.c $(COMMON_FLAGS)

clean:
	@echo "Cleaning up built objects..."
	@rm -Rf $(EXAMPLES)
