CC=gcc
COMMON_FLAGS=`pkg-config --libs --cflags eina,ecore,eldbus`

EXAMPLES= banshee client \
          complex-types \
          complex-types-client-eina-value \
          complex-types-server \
          connman-list-services \
          ofono-dial \
          server \
          simple-signal-emit \
          connect-address

all: examples
examples: $(EXAMPLES)

$(EXAMPLES):
	$(CC) -o $@ $@.c $(COMMON_FLAGS)

clean:
	@echo "Cleaning up built objects..."
	@rm -Rf $(EXAMPLES)
