
# TODO: change code to avoid these
if(EINA_MODULE_TYPE_MP_CHAINED STREQUAL "STATIC")
  SET_GLOBAL(EINA_STATIC_BUILD_CHAINED_POOL 1)
else()
  unset(EINA_STATIC_BUILD_CHAINED_POOL CACHE)
endif()
if(EINA_MODULE_TYPE_MP_ONE_BIG STREQUAL "STATIC")
  SET_GLOBAL(EINA_STATIC_BUILD_ONE_BIG 1)
else()
  unset(EINA_STATIC_BUILD_ONE_BIG CACHE)
endif()
if(EINA_MODULE_TYPE_MP_PASS_THROUGH STREQUAL "STATIC")
  SET_GLOBAL(EINA_STATIC_BUILD_PASS_THROUGH 1)
else()
  unset(EINA_STATIC_BUILD_PASS_THROUGH CACHE)
endif()

configure_file(
  ${CMAKE_CURRENT_SOURCE_DIR}/src/lib/eina/eina_config.h.cmake
  ${CMAKE_CURRENT_BINARY_DIR}/src/lib/eina/eina_config.h)
