FROM base/archlinux

# Install
RUN pacman -Syu
RUN pacman -S --noconfirm git bullet libjpeg-turbo gst-plugins-base \
         luajit curl fribidi libpulse libxcomposite \
         libxinerama libxrandr libxss libinput \
         libxcursor libxp libwebp shared-mime-info \
         libxkbcommon wayland lz4 openjpeg avahi \
         libspectre libraw librsvg wayland-protocols \
         git ninja clang gcc pkgconfig check autoconf make base-devel \
         mesa poppler
