#ifndef EFL_OBJECT_MANUAL_IMPL_HH
#define EFL_OBJECT_MANUAL_IMPL_HH

#define EFL_OBJECT_BETA
#define EFL_OBJECT_PROTECTED

// Skip del. Must be implemented in eo::concrete.
#define EOLIAN_CXX_EFL_DEL_DECLARATION
#define EOLIAN_CXX_EFL_DEL_IMPLEMENTATION

// Skip constructor, destructor and finalize.
#define EOLIAN_CXX_EFL_CONSTRUCTOR_DECLARATION
#define EOLIAN_CXX_EFL_CONSTRUCTOR_IMPLEMENTATION
#define EOLIAN_CXX_EFL_DESTRUCTOR_DECLARATION
#define EOLIAN_CXX_EFL_DESTRUCTOR_IMPLEMENTATION
#define EOLIAN_CXX_EFL_FINALIZE_DECLARATION
#define EOLIAN_CXX_EFL_FINALIZE_IMPLEMENTATION

// Skip auto_unref
#define EOLIAN_CXX_EFL_AUTO_UNREF_SET_DECLARATION
#define EOLIAN_CXX_EFL_AUTO_UNREF_SET_IMPLEMENTATION

#endif
